#!/usr/bin/env bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-SQL
  CREATE EXTENSION IF NOT EXISTS vector;
  CREATE EXTENSION IF NOT EXISTS pg_trgm;

  CREATE SCHEMA IF NOT EXISTS "$GANTRY_SCHEMA";
  CREATE SCHEMA IF NOT EXISTS "$PGBOSS_SCHEMA";

  DO \$\$ BEGIN
    CREATE ROLE "$GANTRY_DB_USER" LOGIN PASSWORD '$GANTRY_DB_PASSWORD';
  EXCEPTION WHEN duplicate_object THEN
    ALTER ROLE "$GANTRY_DB_USER" WITH LOGIN PASSWORD '$GANTRY_DB_PASSWORD';
  END \$\$;

  GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO "$GANTRY_DB_USER";
  GRANT CREATE ON DATABASE "$POSTGRES_DB" TO "$GANTRY_DB_USER";
  REVOKE CREATE ON SCHEMA public FROM PUBLIC;

  ALTER SCHEMA "$GANTRY_SCHEMA" OWNER TO "$GANTRY_DB_USER";
  ALTER SCHEMA "$PGBOSS_SCHEMA" OWNER TO "$GANTRY_DB_USER";

  REVOKE ALL ON SCHEMA "$GANTRY_SCHEMA" FROM PUBLIC;
  REVOKE ALL ON SCHEMA "$PGBOSS_SCHEMA" FROM PUBLIC;

  GRANT USAGE, CREATE ON SCHEMA "$GANTRY_SCHEMA" TO "$GANTRY_DB_USER";
  GRANT USAGE, CREATE ON SCHEMA "$PGBOSS_SCHEMA" TO "$GANTRY_DB_USER";
  GRANT USAGE ON SCHEMA public TO "$GANTRY_DB_USER";
SQL
