#!/usr/bin/env bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-SQL
  CREATE EXTENSION IF NOT EXISTS vector;
  CREATE EXTENSION IF NOT EXISTS pg_trgm;

  CREATE SCHEMA IF NOT EXISTS "$MYCLAW_SCHEMA";
  CREATE SCHEMA IF NOT EXISTS "$ONECLI_SCHEMA";
  CREATE SCHEMA IF NOT EXISTS "$PGBOSS_SCHEMA";

  DO \$\$ BEGIN
    CREATE ROLE "$MYCLAW_DB_USER" LOGIN PASSWORD '$MYCLAW_DB_PASSWORD';
  EXCEPTION WHEN duplicate_object THEN
    ALTER ROLE "$MYCLAW_DB_USER" WITH LOGIN PASSWORD '$MYCLAW_DB_PASSWORD';
  END \$\$;

  DO \$\$ BEGIN
    CREATE ROLE "$ONECLI_DB_USER" LOGIN PASSWORD '$ONECLI_DB_PASSWORD';
  EXCEPTION WHEN duplicate_object THEN
    ALTER ROLE "$ONECLI_DB_USER" WITH LOGIN PASSWORD '$ONECLI_DB_PASSWORD';
  END \$\$;

  GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO "$MYCLAW_DB_USER", "$ONECLI_DB_USER";
  GRANT CREATE ON DATABASE "$POSTGRES_DB" TO "$MYCLAW_DB_USER";
  REVOKE CREATE ON SCHEMA public FROM PUBLIC;

  ALTER SCHEMA "$MYCLAW_SCHEMA" OWNER TO "$MYCLAW_DB_USER";
  ALTER SCHEMA "$PGBOSS_SCHEMA" OWNER TO "$MYCLAW_DB_USER";
  ALTER SCHEMA "$ONECLI_SCHEMA" OWNER TO "$ONECLI_DB_USER";

  REVOKE ALL ON SCHEMA "$MYCLAW_SCHEMA" FROM PUBLIC;
  REVOKE ALL ON SCHEMA "$ONECLI_SCHEMA" FROM PUBLIC;
  REVOKE ALL ON SCHEMA "$PGBOSS_SCHEMA" FROM PUBLIC;

  GRANT USAGE, CREATE ON SCHEMA "$MYCLAW_SCHEMA" TO "$MYCLAW_DB_USER";
  GRANT USAGE, CREATE ON SCHEMA "$PGBOSS_SCHEMA" TO "$MYCLAW_DB_USER";
  GRANT USAGE, CREATE ON SCHEMA "$ONECLI_SCHEMA" TO "$ONECLI_DB_USER";
  GRANT USAGE ON SCHEMA public TO "$MYCLAW_DB_USER", "$ONECLI_DB_USER";

  ALTER ROLE "$ONECLI_DB_USER" IN DATABASE "$POSTGRES_DB"
    SET search_path = "$ONECLI_SCHEMA", public;
SQL
