import { Bot } from 'grammy';
import { ChannelAdapter, ChannelOpts } from '../channel-provider.js';
import type { RuntimeLease } from '../../domain/ports/runtime-lease.js';
import { MessageDeliveryResult, PermissionApprovalCancellation, PermissionApprovalDecision, PermissionApprovalRequest, ProgressUpdateOptions, StreamingChunkOptions, UserQuestionRequest, UserQuestionResponse, MessageSendOptions } from '../../domain/types.js';
import { AsyncTaskQueue } from '../../app/bootstrap/async-task-queue.js';
import { TelegramContext, TelegramStreamApi, ActiveDraftStreamState, ActiveGroupStreamState, ActiveProgressState, PendingUserQuestionState, TelegramUserQuestionCallbackTarget } from './channel-shared.js';
import { StreamResetEpochs } from '../stream-reset-epochs.js';
import { type PendingPermission } from './channel-permission-cancellation.js';
export declare abstract class TelegramChannelState implements ChannelAdapter {
    name: string;
    protected bot: Bot<TelegramContext> | null;
    protected draftStreamApi: TelegramStreamApi | null;
    protected isStopping: boolean;
    protected pollingRetryTimer: ReturnType<typeof setTimeout> | null;
    protected pollingLease: RuntimeLease | null;
    protected pollingStartInFlight: boolean;
    protected interactionCallbacksEnabled: boolean;
    protected opts: ChannelOpts;
    protected botToken: string;
    protected pendingPermissionPrompts: Map<string, PendingPermission>;
    protected pendingUserQuestionCallbackIds: Map<string, TelegramUserQuestionCallbackTarget>;
    protected pendingUserQuestions: Map<string, PendingUserQuestionState>;
    protected pendingUserQuestionOtherPrompts: Map<string, TelegramUserQuestionCallbackTarget>;
    protected pendingTodos: Map<string, {
        chatId: string;
        messageId: number;
    }>;
    protected activeDraftStreams: Map<string, ActiveDraftStreamState>;
    protected activeGroupStreams: Map<string, ActiveGroupStreamState>;
    protected streamGenerationByJid: Map<string, number>;
    protected sealedStreamGenerationByJid: Map<string, number>;
    protected readonly streamResetEpochs: StreamResetEpochs;
    protected activeProgressMessages: Map<string, ActiveProgressState>;
    protected sealedProgressGenerationByKey: Map<string, number>;
    private progressStateLoaded;
    protected mediaIngestionQueue: AsyncTaskQueue;
    protected nextDraftIdOffset: number;
    dropPendingInteraction(kind: 'permission' | 'question', request: PermissionApprovalRequest | UserQuestionRequest): void;
    cancelPendingPermission(cancellation: PermissionApprovalCancellation): Promise<'settled' | 'already_decided' | 'retryable' | 'not_found'>;
    protected abstract claimAndResolvePermissionPrompt(providerAlias: string, mode: NonNullable<PermissionApprovalDecision['mode']>, approverRef: string, reason: string): Promise<'settled' | 'already_decided' | 'ownerless' | 'retryable'>;
    constructor(botToken: string, opts: ChannelOpts);
    supportsInteractionCallbacks(): boolean;
    protected sanitizeErrorMessage(err: unknown): string;
    protected sanitizeTelegramFilePath(rawPath: string): string | null;
    protected clearPollingRetryTimer(): void;
    protected buildDraftStreamKey(jid: string, threadId?: string): string;
    protected loadPersistedProgressMessages(): void;
    protected persistProgressMessages(): void;
    protected shouldAcceptProgressUpdate(key: string, generation?: number, done?: boolean): boolean;
    protected markProgressGenerationDone(key: string, generation?: number): void;
    private progressStateFilePath;
    protected clearStreamingStateForJid(jid: string): void;
    resetStreaming(jid: string, options?: {
        threadId?: string;
    }): void;
    protected shouldAcceptStreamingChunk(jid: string, generation?: number): boolean;
    protected isCurrentStreamingGeneration(jid: string, generation?: number): boolean;
    protected markStreamingGenerationDone(jid: string, generation?: number): void;
    protected sealStreamingGenerationOnReset(jid: string): void;
    protected isLikelyPrivateChatId(numericId: string): boolean;
    protected createDraftChunkStream(): {
        iterator: AsyncIterable<string>;
        push: (chunk: string) => void;
        close: () => void;
    };
    private telegramRateLimitRetryDelayMs;
    private withTelegramGroupRateLimitRetry;
    protected handleGroupStreamingChunk(jid: string, numericId: string, text: string, options: StreamingChunkOptions): Promise<boolean>;
    protected schedulePollingRetry(): void;
    protected abstract startPolling(): void;
    abstract connect(): Promise<void>;
    abstract sendMessage(jid: string, text: string, options?: MessageSendOptions): Promise<MessageDeliveryResult>;
    abstract sendStreamingChunk(jid: string, text: string, options?: StreamingChunkOptions): Promise<boolean>;
    abstract sendProgressUpdate(jid: string, text: string, options?: ProgressUpdateOptions): Promise<void>;
    abstract requestPermissionApproval(jid: string, request: PermissionApprovalRequest, onPromptDelivered?: (messageId: string) => void): Promise<PermissionApprovalDecision>;
    abstract requestUserAnswer(jid: string, request: UserQuestionRequest, onPromptDelivered?: (messageId: string) => void): Promise<UserQuestionResponse>;
    abstract isConnected(): boolean;
    abstract ownsJid(jid: string): boolean;
    abstract disconnect(): Promise<void>;
    abstract setTyping(jid: string, isTyping: boolean): Promise<void>;
}
