import type { AgentInput } from './agent-spawn-types.js';
import type { EgressGatewayPrivateHostMapping } from './egress-gateway.js';
import type { RunnerSandboxProvider, RunnerSandboxProviderId, RunnerSandboxResourceLimits, RunnerSandboxSpawnInput, RunnerSandboxWarmTemplateStatus } from '../shared/runner-sandbox-provider.js';
import { type DeepAgentsShellFilesystemGuardInput } from './deepagents-shell-filesystem-guard.js';
export declare function deepAgentsShellEnabledEnv(input: DeepAgentsShellFilesystemGuardInput): Record<string, string>;
export declare function deepAgentsFilesystemEnabledEnv(input: DeepAgentsShellFilesystemGuardInput): Record<string, string>;
export type RunnerAgentInput = Omit<AgentInput, 'toolPolicyRules'> & {
    allowedTools?: string[];
    egressDenylist?: string[];
    modelCredentialEnv?: Record<string, string>;
    toolNetworkEnv?: Record<string, string>;
    deepAgentCheckpointer?: {
        databaseUrl: string;
        schema: string;
        proxyUrl?: string;
    };
};
export declare function buildBaseRunnerEnv(input: {
    hostEnv: NodeJS.ProcessEnv;
    preparedEnv: NodeJS.ProcessEnv;
    runnerToolProcessEnv: Record<string, string>;
    runnerTempDir?: string;
    preparedTempEnv?: NodeJS.ProcessEnv;
    timezone: string;
    mcpServerPath: string;
    hostRuntimeGroupDir: string;
    workspaceKey: string;
    runnerAppId: string;
    agentId?: string;
    processName: string;
    workspaceExtraDir: string;
    workspaceIpcDir: string;
    ipcInputDir: string;
    ipcAuthToken: string;
    chatJid: string;
    providerAccountId?: string;
    jobId?: string;
    jobName?: string;
    runId?: string;
    parentTaskId?: string;
    runLeaseToken?: string;
    runLeaseFencingVersion?: number;
    liveStopActionToken?: string;
    browserIpcAuthToken?: string;
    memoryIpcAuthToken: string;
    memoryIpcAllowedActions: readonly string[];
    responseVerifyKey: string;
    responseKeyId: string;
    threadId?: string;
    memoryUserId?: string;
    memoryDefaultScope?: string;
    memoryReviewerIsControlApprover?: boolean;
    hideAuthorityTools: boolean;
    agentAccessPreset: string;
    deploymentMode: string;
    permissionMode: NonNullable<AgentInput['permissionMode']>;
    permissionLane: 'interactive' | 'autonomous';
    turnIntentSummary: string;
    permissionTimeoutMs: number;
    egressProxyUrl: string;
    sandboxRuntimeProxy: boolean;
    deepAgentsShellEnv: Record<string, string>;
    deepAgentsFilesystemEnv: Record<string, string>;
    pickSafeHostEnv: (env: NodeJS.ProcessEnv) => NodeJS.ProcessEnv;
    pickPreparedExecutionEnv: (env: NodeJS.ProcessEnv) => NodeJS.ProcessEnv;
}): NodeJS.ProcessEnv;
type WarnLogger = (metadata: Record<string, unknown>, message: string) => void;
type SandboxRuntimeNetworkProjection = {
    allowedNetworkHosts?: string[];
    privateNetworkHostMappings?: readonly EgressGatewayPrivateHostMapping[];
};
export declare function resolveRunnerSandboxStartup(input: {
    provider?: RunnerSandboxProvider;
    runtimeProvider: RunnerSandboxProviderId;
    measure: <T>(phase: 'sandboxTemplateMs', run: () => T) => T;
}): {
    runnerSandboxProviderId: RunnerSandboxProviderId;
    sandboxWarmTemplate: RunnerSandboxWarmTemplateStatus;
};
export declare function uniqueStrings(values: readonly string[]): string[];
export declare function prepareRunnerWorkspace(input: {
    folder: string;
    nowMs: () => number;
    warn: WarnLogger;
}): {
    groupDir: string;
    processName: string;
};
export declare function cleanupRunnerMcpConfigFile(configPath: string | undefined, warn: WarnLogger): void;
export declare function cleanupRunnerTempDir(dir: string | undefined, warn: WarnLogger): void;
export declare function protectedWritePathsForOuterSandbox(protectedPaths: readonly string[], providerConfigDir: string | undefined): string[];
export declare function sandboxRuntimeToolProcessEnv(providerId: string, toolNetworkEnv: Record<string, string>): Record<string, string>;
export declare function sandboxRuntimeToolNetworkEnv(providerId: string, toolNetworkEnv: Record<string, string>): Record<string, string>;
export declare function buildSandboxRuntimeNetworkProjection(providerId: string, allowedNetworkHosts: readonly string[], modelCredentialEnv: Record<string, string> | undefined): {
    modelCredentialEnv: Record<string, string> | undefined;
    networkProjection: SandboxRuntimeNetworkProjection;
};
export declare function buildRunnerSandboxSpawnInput(input: {
    groupDir: string;
    sandboxConfigPath: string;
    egressProxyUrl?: string;
    allowedNetworkHosts: readonly string[];
    runnerPackageRoot: string;
    workspaceIpcDir: string;
    workspaceExtraDir: string;
    providerConfigDir?: string;
    runnerTempDir?: string;
    providerToolTempDir?: string;
    localCliCredentialPaths: readonly string[];
    mcpConfigPath?: string;
    protectedReadPaths: readonly string[];
    protectedWritePaths: readonly string[];
    resourceLimits: RunnerSandboxResourceLimits;
    principal: {
        appId: string;
        agentId?: string;
        conversationId: string;
        threadId?: string;
        runId?: string;
        jobId?: string;
    };
}): Omit<RunnerSandboxSpawnInput, 'command' | 'args' | 'env'>;
export declare function buildAndLogRunnerRuntimeDetails(input: {
    logger: {
        debug: (context: Record<string, unknown>, message: string) => void;
        info: (context: Record<string, unknown>, message: string) => void;
    };
    groupName: string;
    processName: string;
    command: string;
    args: readonly string[];
    groupDir: string;
    ipcInputDir: string;
    sandboxProviderId: string;
    sandboxEnforcing: boolean;
    brokerProfile: string;
    brokerApplied: boolean;
    mcpServerNames: readonly string[];
    browserProfileName: string;
    preparedRuntimeDetails: readonly string[];
    effectiveModel?: string;
    effectiveModelSource?: string;
    systemPromptChars: number;
}): string[];
export {};
