import type { ConversationRoute } from '../domain/types.js';
import type { AgentInput } from './agent-spawn-types.js';
export declare function resolveSpawnAgentId(input: {
    inputAgentId?: string;
    routeAgentId?: string;
    workspaceFolder: string;
}): string;
export declare function resolveAgentSpawnLogContext(group: ConversationRoute, input: AgentInput, correlationRunId?: string): {
    agentName: string;
    turn: {
        appId: string;
        agentId: string;
        prompt: string;
        model?: string;
        sessionId?: string;
        workspaceFolder: string;
        chatJid: string;
        threadId?: string;
        memoryUserId?: string;
        memoryDefaultScope?: "user" | "group";
        memoryReviewerIsControlApprover?: boolean;
        persona?: import("../shared/agent-persona.js").AgentPersona;
        browserProfileName?: string;
        toolPolicyRules?: string[];
        toolRules?: import("./agent-spawn-types.js").AgentToolRule[];
        toolAccessRequirements?: string[];
        attachedSkillSourceIds?: string[];
        selectedSkillDisplays?: string[];
        attachedMcpSourceIds?: string[];
        semanticCapabilities?: import("../shared/semantic-capabilities.js").SemanticCapabilityDefinition[];
        capabilityCatalog?: import("../application/agents/agent-prompt-capability-catalog.js").AgentPromptCapabilityCatalog;
        providerSessionAccessFingerprint?: string;
        hideAuthorityTools?: boolean;
        isScheduledJob?: boolean;
        jobId?: string;
        jobName?: string;
        runId?: string;
        parentRunId?: string;
        parentTaskId?: string;
        callableAgentManifest?: import("../shared/callable-agent-manifest.js").CallableAgentToolManifestEntry[];
        runLeaseToken?: string;
        runLeaseFencingVersion?: number;
        liveStopActionToken?: string;
        jobModelUseKind?: "oneTimeJob" | "recurringJob";
        assistantName?: string;
        compiledSystemPrompt?: string;
        thinking?: import("../domain/types.js").ThinkingOverride;
        effort?: import("../domain/types.js").AgentControlEffort;
        configuredThinking?: import("../domain/types.js").AgentControlThinking;
        maxOutputTokens?: number;
        memoryContextBlock?: string;
        yoloMode?: import("../shared/yolo-mode-policy.js").YoloModeSettings;
        permissionMode?: import("../shared/permission-mode.js").PermissionMode;
        runtimeAccess?: import("../shared/capability-runtime-access.js").CapabilityRuntimeAccess[];
        runtime?: import("../shared/agent-runtime.js").AgentRuntime;
        deepAgentSkills?: import("../application/agent-execution/agent-execution-adapter.js").DeepAgentSkillProjection;
        responseSchema?: Record<string, unknown>;
    };
    correlationRunId: string | undefined;
    appId: string;
    agentId: string;
};
export declare function stripIncompleteRunLeaseIdentity(input: AgentInput): AgentInput;
