import type { ChildProcess } from 'child_process';
import { type GroupQueuePolicy } from './group-queue-policy.js';
import { type ContinuationHandler, type ContinuationOptions, type GroupQueueOptions, type ProcessMessagesFn, type QueuedTask } from './group-queue-types.js';
import type { LiveTurnLocalRunnerHooks } from './live-turn-authority.js';
export declare class GroupQueue {
    private readonly policy;
    private readonly setTimeoutFn;
    private readonly runnerControlPort;
    private groups;
    private stopAliases;
    private activeMessageCount;
    private activeTaskCount;
    private waitingMessageGroups;
    private waitingTaskGroups;
    private continuationSequence;
    private processMessagesFn;
    private liveTurnRunnerRegistrar;
    private shuttingDown;
    private activeRuns;
    constructor(options?: GroupQueueOptions);
    getPolicy(): GroupQueuePolicy;
    isShuttingDown(): boolean;
    private getGroup;
    private deleteGroupIfIdle;
    setProcessMessagesFn(fn: ProcessMessagesFn): void;
    setLiveTurnRunnerRegistrar(registrar: ((queueJid: string, hooks: LiveTurnLocalRunnerHooks, routing: {
        stopAliasJids?: string[];
        requiredContinuationUserId?: string | null;
    }) => Promise<void> | void) | null): void;
    private addStopAlias;
    private removeStopAliasForQueueJid;
    private cleanupEphemeralGroupIfIdle;
    private enqueueWaitingGroup;
    private canAcceptWaitingMessageGroup;
    private refillWaitingMessageBacklog;
    private pendingTaskCount;
    private canAcceptPendingTask;
    private rejectTaskBacklog;
    private dequeueWaitingGroup;
    enqueueMessageCheck(groupJid: string): boolean;
    enqueueTask(groupJid: string, taskId: string, fn: () => Promise<void>, options?: {
        admissionClass?: QueuedTask['admissionClass'];
    }): boolean;
    private trackRun;
    private waitForActiveRuns;
    private closeActiveMessageRunsForShutdown;
    registerProcess(groupJid: string, proc: ChildProcess, runHandle: string, workspaceFolder?: string, stopAliasJids?: string | string[], threadId?: string | null, options?: {
        requiredContinuationUserId?: string | null;
    }): void;
    notifyIdle(groupJid: string): void;
    registerContinuationHandler(groupJid: string, handler: ContinuationHandler): () => void;
    sendMessage(groupJid: string, text: string, options?: ContinuationOptions): boolean;
    closeStdin(groupJid: string): void;
    stopGroup(groupJid: string): boolean;
    isGroupActive(groupJid: string): boolean;
    private runForGroup;
    private runTask;
    private scheduleRetry;
    private drainGroup;
    private drainWaiting;
    shutdown(gracePeriodMs: number): Promise<void>;
}
