export function formatSessionCommandsHelp(): string {
  return [
    'Gantry commands',
    'Use /gantry to discover commands. Direct commands like /stop still work.',
    'In threads where slash commands are not available, use !stop, !status, or !new.',
    '',
    'Session',
    '/gantry commands, /commands, or !commands - List available chat commands.',
    '/gantry new, /new, or !new - Start a fresh session while preserving durable memory and approved capabilities.',
    '/gantry compact, /compact, or !compact - Compact the current provider context and collect durable memory.',
    '/gantry stop, /stop, or !stop - Stop the active run for this conversation.',
    '',
    'Models',
    '/gantry model, /model, or !model - Show the current model selection.',
    '/gantry model <alias>, /model <alias>, or !model <alias> - Set the conversation model override.',
    '/gantry model why <alias|family>, /model why <alias|family>, or !model why <alias|family> - Explain a model route and availability.',
    '/gantry model default, /model default, or !model default - Clear the conversation model override.',
    '/gantry models, /models, or !models - List available model aliases.',
    '',
    'Status',
    '/gantry status, /status, or !status - Show model/runtime status for this conversation.',
    '/gantry memory-status, /memory-status, or !memory-status - Show durable memory status.',
    '/gantry dream, /dream, or !dream - Run memory dreaming now when enabled.',
    '',
    'Thinking',
    '/gantry thinking, /thinking, or !thinking - Show the current thinking setting.',
    '/gantry thinking <low|medium|high|max|adaptive|enabled|off>, /thinking <...>, or !thinking <...> - Set thinking for this conversation.',
    '/gantry thinking default, /thinking default, or !thinking default - Clear the thinking override.',
    '',
    'Permissions',
    '/gantry permissions, /permissions, or !permissions - Show the current permission mode.',
    '/gantry permissions <ask|auto|auto_strict>, /permissions <ask|auto|auto_strict>, or !permissions <ask|auto|auto_strict> - Set the permission mode for this conversation.',
    '/gantry permissions default, /permissions default, or !permissions default - Clear the permission mode override.',
    '',
    'Memory',
    '/gantry save-procedure "<title>" or /save-procedure "<title>" - Save reusable procedure steps from the message body or recent context.',
    '',
    'In-house agent surfaces',
    'gantry-admin - Runtime administration reference for approved Gantry admin tools.',
    'gantry-browser - Browser gateway guidance when the Browser capability is selected.',
  ].join('\n');
}
