export function formatSessionCommandsHelp(): string {
  return [
    'Gantry commands',
    'In Slack, mention the agent with !<command> when slash commands are intercepted by Slack, for example: @Gantry !new.',
    '',
    'Session',
    '/commands or !commands - List available chat commands.',
    '/new or !new - Start a fresh session while preserving durable memory and approved capabilities.',
    '/compact or !compact - Compact the current provider context and collect durable memory.',
    '/stop or !stop - Stop the active run for this conversation.',
    '',
    'Models',
    '/model or !model - Show the current model selection.',
    '/model <alias> or !model <alias> - Set the conversation model override.',
    '/model default or !model default - Clear the conversation model override.',
    '/models or !models - List available model aliases.',
    '',
    'Status',
    '/status or !status - Show model/runtime status for this conversation.',
    '/memory-status or !memory-status - Show durable memory status.',
    '/dream or !dream - Run memory dreaming now when enabled.',
    '',
    'Thinking',
    '/thinking or !thinking - Show the current thinking setting.',
    '/thinking <low|medium|high|max|adaptive|enabled|off> or !thinking <...> - Set thinking for this conversation.',
    '/thinking default or !thinking default - Clear the thinking override.',
    '',
    'Memory',
    '/save-procedure "<title>" - Save reusable procedure steps from the message body or recent context.',
    '',
    'In-house agent surfaces',
    'gantry-admin - Runtime administration reference for approved Gantry admin tools.',
    'gantry-browser - Browser gateway guidance when the Browser capability is selected.',
  ].join('\n');
}
