export declare const DEEPAGENTS_ENGINE = "deepagents";
export declare const DEFAULT_AGENT_ENGINE = "anthropic_sdk";
export declare const AGENT_ENGINES: readonly ["anthropic_sdk", "deepagents"];
export type AgentEngine = (typeof AGENT_ENGINES)[number];
export declare const AUTO_AGENT_HARNESS = "auto";
export declare const AGENT_HARNESSES: readonly ["auto", "anthropic_sdk", "deepagents"];
export type AgentHarness = (typeof AGENT_HARNESSES)[number];
export declare function agentEngineLabel(engine: AgentEngine): string;
export declare function isAgentEngine(value: unknown): value is AgentEngine;
export declare function isAgentHarness(value: unknown): value is AgentHarness;
