export declare const PROVIDER_CONFIG_DIR_SEGMENT: string;
export declare const PROVIDER_CLI_NAME: string;
export declare function firstProtectedPathMention(command: string): string | undefined;
export declare function allProtectedPathMentions(command: string): string[];
export declare function isProtectedCapabilityPathLike(filePath: string): boolean;
export declare function protectedCapabilityPathMatch(filePath: string): string | undefined;
export declare function isSkillCapabilityPath(value: string): boolean;
export declare function isMcpCapabilityPath(value: string): boolean;
export declare function isProviderSettingsPath(value: string): boolean;
export declare function isRuntimeSettingsPath(value: string): boolean;
export declare function hasProtectedPathReference(value: string): boolean;
