import type { CreateMemoryReviewOutcome, MemoryReviewDb } from './app-memory-review-create.js';
import type { DreamDecisionAction, MemoryLifecycleProposal, NormalizedMemorySubject } from './memory-types.js';
type Db = MemoryReviewDb;
export type CreatePendingReview = (p: MemoryLifecycleProposal, db?: Db) => Promise<CreateMemoryReviewOutcome>;
export declare function setCandidateStatus(db: Db, id: string, status: string): Promise<void>;
export declare function recordDreamDecision(input: {
    db: Db;
    runId: string;
    subject: NormalizedMemorySubject;
    action: DreamDecisionAction;
    rationale: string;
    itemId?: string;
    candidateId?: string;
    evidenceIds?: string[];
    applied: boolean;
}): Promise<void>;
export declare function routeMemoryProposalToReview(input: {
    db: Db;
    runId: string;
    subject: NormalizedMemorySubject;
    dryRun: boolean;
    createPendingReview?: CreatePendingReview;
    proposal: MemoryLifecycleProposal;
    candidateId?: string;
    itemId?: string;
    evidenceIds?: string[];
    reviewRationale: string;
    blockRationale: string;
}): Promise<DreamDecisionAction>;
export {};
