export const CAPABILITY_RUN_MAX_ARGS = 64;
export const CAPABILITY_RUN_MAX_ARG_BYTES = 4_096;
export const CAPABILITY_RUN_MAX_TOTAL_ARG_BYTES = 16_384;
export const CAPABILITY_RUN_OUTPUT_MAX_BYTES = 4_000;
