flowchart LR
  OC[OpenClaw<br/>personal / self-hosted]
  NC[NemoClaw<br/>local / private]
  MS[Microsoft Scout<br/>Microsoft 365-native]
  GT[Gantry<br/>embeddable enterprise runtime]

  OC --- NC --- MS --- GT
