import { MessageDeliveryResult, MessageSendOptions, PermissionApprovalCancellation, PermissionApprovalDecision, PermissionApprovalRequest, ProgressUpdateOptions, RichInteractionRequest, StreamingChunkOptions, UserQuestionCancellation, UserQuestionRequest, UserQuestionResponse } from '../domain/types.js';
import type { AgentTodoRender } from '../domain/ports/task-lifecycle.js';
import { ChannelAdapter, ChannelOpts, type ConversationContextHydrationRequest, type ConversationContextHydrationResult } from './channel-provider.js';
import type { WebSocketFactory } from './discord-types.js';
export declare const DISCORD_JID_PREFIX = "dc:";
export declare function normalizeDiscordJid(raw: string): string | null;
export declare function discordChannelIdFromJid(jid: string): string | null;
export declare class DiscordChannel implements ChannelAdapter {
    private readonly botToken;
    private readonly applicationId;
    private readonly opts;
    private readonly createWebSocket;
    name: string;
    private gateway;
    private botUserId;
    private activeProgressMessages;
    private activeStreams;
    private readonly streamGenerationByJid;
    private readonly sealedStreamGenerationByJid;
    private readonly streamResetEpochs;
    private pendingTodos;
    private readonly reactionKeys;
    private readonly messageChannelIds;
    private readonly channelContextCache;
    private readonly interactions;
    constructor(botToken: string, applicationId: string, opts: ChannelOpts, createWebSocket?: WebSocketFactory);
    ownsJid(jid: string): boolean;
    connect(options?: {
        inbound?: boolean;
    }): Promise<void>;
    isConnected(): boolean;
    disconnect(): Promise<void>;
    sendMessage(jid: string, text: string, options?: MessageSendOptions): Promise<MessageDeliveryResult>;
    renderRichInteraction(jid: string, render: RichInteractionRequest): Promise<boolean>;
    addReaction(jid: string, messageRef: string, emoji: string): Promise<void>;
    hydrateConversationContext(request: ConversationContextHydrationRequest): Promise<ConversationContextHydrationResult>;
    sendProgressUpdate(jid: string, text: string, options?: ProgressUpdateOptions): Promise<void>;
    sendStreamingChunk(jid: string, text: string, options?: StreamingChunkOptions): Promise<boolean>;
    resetStreaming(jid: string, options?: {
        threadId?: string;
    }): void;
    private clearStreamingStateForJid;
    private shouldAcceptStreamingChunk;
    private markStreamingGenerationDone;
    private sealStreamingGenerationOnReset;
    renderAgentTodo(jid: string, render: AgentTodoRender): Promise<boolean>;
    requestPermissionApproval(jid: string, request: PermissionApprovalRequest, onPromptDelivered?: (messageId: string) => void): Promise<PermissionApprovalDecision>;
    requestUserAnswer(jid: string, request: UserQuestionRequest, onPromptDelivered?: (messageId: string) => void): Promise<UserQuestionResponse>;
    cancelPendingPermission(cancellation: PermissionApprovalCancellation): Promise<'settled' | 'already_decided' | 'retryable' | 'not_found'>;
    cancelPendingQuestion(cancellation: UserQuestionCancellation): Promise<'settled' | 'already_decided' | 'retryable' | 'not_found'>;
    dropPendingInteraction(kind: 'permission' | 'question', request: PermissionApprovalRequest | UserQuestionRequest): void;
    private requestJson;
    private postJson;
    private postMessage;
    private patchMessage;
    private handleGatewayDispatch;
    private handleMessageCreate;
    private messageChannelKey;
    private rememberMessageChannelId;
    private resolveMessageChannelId;
    private pruneMessageChannelIds;
    private resolveInteractionConversationContext;
}
export declare function createDiscordChannel(opts: ChannelOpts): Promise<ChannelAdapter | null>;
