import { type ChannelAdapter, type ChannelOpts, type ConversationContextHydrationRequest } from './channel-provider.js';
import type { MessageDeliveryResult, MessageSendOptions, PermissionApprovalCancellation, PermissionApprovalDecision, PermissionApprovalRequest, ProgressUpdateOptions, RichInteractionRequest, StreamingChunkOptions, UserQuestionCancellation, UserQuestionRequest, UserQuestionResponse } from '../domain/types.js';
import type { AgentTodoRender } from '../domain/ports/task-lifecycle.js';
import { type TeamsChannelCredentials, type TeamsChannelDependencies, type TeamsChannelOpts, type TeamsInboundMessage, type TeamsSdkClient } from './teams-types.js';
import { teamsDeliveredQuestionIndexes } from './teams-user-question.js';
export { TEAMS_ADAPTIVE_CARD_CONTENT_TYPE, buildTeamsAgentTodoCard, buildTeamsApprovalAdaptiveCard, buildTeamsApprovalDescriptorPayload, buildTeamsUserQuestionCard, buildTeamsUserQuestionReceiptCard, type TeamsAdaptiveCardAction, type TeamsAdaptiveCardDescriptorPayload, type TeamsAdaptiveCardPayload, type TeamsAdaptiveCardSubmitAction, } from './teams-cards.js';
export { TEAMS_JID_PREFIX, isTeamsJid, normalizeTeamsJid, teamsConversationIdFromJid, type TeamsChannelCredentials, type TeamsChannelDependencies, type TeamsInboundMessage, type TeamsSdkClient, } from './teams-types.js';
export declare class TeamsChannel implements ChannelAdapter {
    private readonly credentials;
    private readonly opts;
    private readonly sdkClient;
    name: string;
    private connected;
    private outboundReady;
    private readonly pendingPermissionPrompts;
    private readonly pendingTodos;
    private readonly pendingProgress;
    private readonly activeStreams;
    private readonly streamResetEpochs;
    private readonly streamGenerationByJid;
    private readonly sealedStreamGenerationByJid;
    private readonly pendingUserQuestions;
    constructor(credentials: TeamsChannelCredentials, opts: TeamsChannelOpts, sdkClient: TeamsSdkClient);
    dropPendingInteraction(kind: 'permission' | 'question', request: PermissionApprovalRequest | UserQuestionRequest): void;
    cancelPendingPermission(cancellation: PermissionApprovalCancellation): Promise<'settled' | 'already_decided' | 'retryable' | 'not_found'>;
    cancelPendingQuestion(cancellation: UserQuestionCancellation): Promise<import("./interaction-settlement.js").InteractionCancellationResult>;
    connect(options?: {
        inbound?: boolean;
        interactionCallbacks?: boolean;
    }): Promise<void>;
    isConnected(): boolean;
    disconnect(): Promise<void>;
    ownsJid(jid: string): boolean;
    hydrateConversationContext(request: ConversationContextHydrationRequest): Promise<import("./channel-provider.js").ConversationContextHydrationResult>;
    sendMessage(jid: string, text: string, options?: MessageSendOptions): Promise<MessageDeliveryResult | void>;
    renderRichInteraction(jid: string, render: RichInteractionRequest): Promise<boolean>;
    addReaction(): Promise<void>;
    sendProgressUpdate(jid: string, text: string, options?: ProgressUpdateOptions): Promise<void>;
    sendStreamingChunk(jid: string, text: string, options?: StreamingChunkOptions): Promise<boolean>;
    resetStreaming(jid: string, options?: {
        threadId?: string;
    }): void;
    renderAgentTodo(jid: string, render: AgentTodoRender): Promise<boolean>;
    private streamKey;
    private clearStreamingStateForJid;
    private shouldAcceptStreamingChunk;
    private markStreamingGenerationDone;
    private sealStreamingGenerationOnReset;
    ingestMessage(message: TeamsInboundMessage): Promise<void>;
    requestPermissionApproval(jid: string, request: PermissionApprovalRequest, onPromptDelivered?: (messageId: string) => void): Promise<PermissionApprovalDecision>;
    requestUserAnswer(jid: string, request: UserQuestionRequest, onPromptDelivered?: (messageId: string, questionIndex?: number) => void): Promise<UserQuestionResponse>;
    questionIndexesForDeliveredPrompt: typeof teamsDeliveredQuestionIndexes;
    private handleUserQuestionSubmit;
    private handleMessageAction;
    private resolvePendingUserQuestion;
    private handlePermissionDecision;
    private interactionContext;
}
export declare function createTeamsChannel(opts: ChannelOpts, deps?: TeamsChannelDependencies): Promise<TeamsChannel | null>;
