import path from 'path';

import { readEnvFile } from '../cli/env-file.js';
import { getMyclawHome } from './myclaw-home.js';

export const CONFIG_ENV_KEYS = [
  'MYCLAW_HOME',
  'ASSISTANT_NAME',
  'ONECLI_URL',
  'TZ',
  'ANTHROPIC_MODEL',
  'ANTHROPIC_API_KEY',
  'ANTHROPIC_AUTH_TOKEN',
  'ANTHROPIC_BASE_URL',
  'CLAUDE_CODE_OAUTH_TOKEN',
  'OPENAI_API_KEY',
  'OPENAI_BASE_URL',
  'OPENAI_ORG_ID',
  'OPENAI_PROJECT',
  'OPENAI_DAILY_EMBED_LIMIT',
  'MEMORY_KNOWLEDGE_EMBED_BUDGET_PER_DAY',
  'MEMORY_CHUNK_SIZE',
  'MEMORY_CHUNK_OVERLAP',
  'MEMORY_RETRIEVAL_LIMIT',
  'MEMORY_RETRIEVAL_MIN_SCORE',
  'MEMORY_TEMPORAL_DECAY_HALFLIFE_DAYS',
  'MEMORY_MMR_LAMBDA',
  'MEMORY_RRF_LEXICAL_WEIGHT',
  'MEMORY_RRF_VECTOR_WEIGHT',
  'MEMORY_SOURCE_TYPE_BOOSTS',
  'MEMORY_EXTRACTOR_MAX_FACTS',
  'MEMORY_EXTRACTOR_MIN_CONFIDENCE',
  'MEMORY_EXTRACTOR_MAX_TURNS',
  'MEMORY_REFLECTION_MIN_CONFIDENCE',
  'MEMORY_REFLECTION_MAX_FACTS_PER_TURN',
  'MEMORY_SCOPE_POLICY',
  'MEMORY_RETENTION_PIN_THRESHOLD',
  'MEMORY_ITEM_MAX_PER_GROUP',
  'MEMORY_SEMANTIC_DEDUP_ENABLED',
  'MEMORY_SEMANTIC_DEDUP_THRESHOLD',
  'MEMORY_GLOBAL_KNOWLEDGE_DIR',
  'MEMORY_MAX_GLOBAL_CHUNKS',
  'MEMORY_USAGE_FEEDBACK_ENABLED',
  'MEMORY_CONFIDENCE_BOOST_ON_USE',
  'MEMORY_CONFIDENCE_DECAY_ON_UNUSED',
  'MEMORY_USAGE_DECAY_INTERVAL_TURNS',
  'MEMORY_CONSOLIDATION_MIN_ITEMS',
  'MEMORY_CONSOLIDATION_CLUSTER_THRESHOLD',
  'MEMORY_CONSOLIDATION_EMBEDDING_FALLBACK',
  'MEMORY_CONSOLIDATION_MAX_CLUSTERS',
  'MEMORY_DREAMING_CRON',
  'MEMORY_DREAMING_DRY_RUN',
  'MEMORY_DREAMING_PROMOTION_THRESHOLD',
  'MEMORY_DREAMING_DECAY_THRESHOLD',
  'MEMORY_DREAMING_MIN_RECALLS',
  'MEMORY_DREAMING_MIN_UNIQUE_QUERIES',
  'MEMORY_DREAMING_CONFIDENCE_BOOST',
  'MEMORY_DREAMING_CONFIDENCE_DECAY',
  'MEMORY_EMBED_BATCH_SIZE',
  'MEMORY_VECTOR_DIMENSIONS',
  'MEMORY_MAX_CHUNKS_PER_GROUP',
  'MEMORY_CHUNK_RETENTION_DAYS',
  'MEMORY_MAX_EVENTS',
  'MEMORY_MAX_PROCEDURES_PER_GROUP',
  'MEMORY_CLEANUP_PURGE_DAYS',
  'MEMORY_JOURNAL_GZIP_DAYS',
  'MEMORY_JOURNAL_DELETE_DAYS',
  'MEMORY_MAINTENANCE_MAX_PENDING',
  'MYCLAW_MEMORY_JOURNAL_DISABLED',
  'MEMORY_BRIEF_INCLUDE_LAST_SESSION',
  'MEMORY_BRIEF_DIRTY_REFRESH',
  'MYCLAW_CREDENTIAL_MODE',
  'MYCLAW_IPC_AUTH_SECRET',
  'REMOTE_CONTROL_AUTO_ACCEPT',
  'CHROME_PATH',
  'SSL_CERT_FILE',
  'NODE_EXTRA_CA_CERTS',
  'HTTP_PROXY',
  'HTTPS_PROXY',
  'NO_PROXY',
  'LOG_LEVEL',
  'PERMISSION_APPROVAL_TIMEOUT_MS',
  'TELEGRAM_BOT_TOKEN',
  'TELEGRAM_PERMISSION_APPROVER_IDS',
  'SLACK_BOT_TOKEN',
  'SLACK_APP_TOKEN',
  'SLACK_PERMISSION_APPROVER_IDS',
] as const;

function loadRuntimeEnvConfig(keys: readonly string[]): Record<string, string> {
  const envFilePath = path.join(getMyclawHome(), '.env');
  const raw = readEnvFile(envFilePath);
  const out: Record<string, string> = {};
  for (const key of keys) {
    const value = raw[key]?.trim();
    if (value) {
      out[key] = value;
    }
  }
  return out;
}

export const envConfig = loadRuntimeEnvConfig(CONFIG_ENV_KEYS);

export function envValue(key: (typeof CONFIG_ENV_KEYS)[number]): string {
  return process.env[key]?.trim() || envConfig[key]?.trim() || '';
}
