export declare const RUNTIME_EVENT_TYPES: {
    readonly SESSION_MESSAGE_INBOUND: "session.message.inbound";
    readonly SESSION_MESSAGE_OUTBOUND: "session.message.outbound";
    readonly SESSION_MESSAGE_STREAMING: "session.message.streaming";
    readonly SESSION_TYPING: "session.typing";
    readonly SESSION_PROGRESS: "session.progress";
    readonly SESSION_COMPACTION_QUEUED: "session.compaction.queued";
    readonly SESSION_COMPACTION_RUNNING: "session.compaction.running";
    readonly SESSION_COMPACTION_READY: "session.compaction.ready";
    readonly SESSION_COMPACTION_DEGRADED: "session.compaction.degraded";
    readonly SESSION_COMPACTION_FAILED: "session.compaction.failed";
    readonly SESSION_COMPACTION_TIMEOUT: "session.compaction.timeout";
    readonly CONVERSATION_MESSAGE_INBOUND: "conversation.message.inbound";
    readonly CONVERSATION_MESSAGE_OUTBOUND: "conversation.message.outbound";
    readonly JOB_TRIGGERED: "job.triggered";
    readonly JOB_RUN_STARTED: "job.run.started";
    readonly JOB_STARTED: "job.started";
    readonly JOB_STREAMING: "job.streaming";
    readonly JOB_HEARTBEAT: "job.heartbeat";
    readonly JOB_SETUP_REQUIRED: "job.setup_required";
    readonly JOB_TOOL_DENIED: "job.tool_denied";
    readonly JOB_TOOL_ACTIVITY: "job.tool_activity";
    readonly TASK_STARTED: "task.started";
    readonly TASK_PROGRESS: "task.progress";
    readonly TASK_UPDATED: "task.updated";
    readonly TASK_NOTIFICATION: "task.notification";
    readonly JOB_COMPLETED: "job.completed";
    readonly JOB_FAILED: "job.failed";
    readonly JOB_RUN_COMPLETED: "job.run.completed";
    readonly JOB_RUN_FAILED: "job.run.failed";
    readonly PERMISSION_REQUESTED: "permission.requested";
    readonly PERMISSION_ALLOWED: "permission.allowed";
    readonly PERMISSION_DENIED: "permission.denied";
    readonly PERMISSION_CANCELLED: "permission.cancelled";
    readonly PERMISSION_PERSISTED: "permission.persisted";
    readonly PERMISSION_RESUMED: "permission.resumed";
    readonly PERMISSION_FINAL_OUTCOME: "permission.final_outcome";
    readonly PERMISSION_YOLO_DENYLIST_HIT: "permission.yolo_denylist_hit";
    readonly PERMISSION_CLASSIFIER_DECISION: "permission.classifier_decision";
    readonly INTERACTION_PENDING: "interaction.pending";
    readonly INTERACTION_CANCELLATION_DISCARDED: "interaction.cancellation_discarded";
    readonly CREDENTIAL_CAPABILITY_UPDATED: "credential.capability.updated";
    readonly CREDENTIAL_CAPABILITY_REMOVED: "credential.capability.removed";
    readonly CREDENTIAL_MODEL_UPDATED: "credential.model.updated";
    readonly CREDENTIAL_MODEL_DISABLED: "credential.model.disabled";
    readonly CREDENTIAL_MODEL_USED: "credential.model.used";
    readonly PROFILE_FILE_READ: "profile.file.read";
    readonly PROFILE_FILE_UPDATED: "profile.file.updated";
    readonly EGRESS_CONNECT: "egress.connect";
    readonly MCP_TOOL_ACTIVITY: "mcp.tool_activity";
    readonly SANDBOX_BLOCKED: "sandbox.blocked";
    readonly MODEL_USAGE: "model.usage";
    readonly RUN_STARTED: "run.started";
    readonly RUN_STARTUP_DIAGNOSTIC: "run.startup_diagnostic";
    readonly RUN_FAILOVER: "run.failover";
    readonly RUN_CANCELED: "run.canceled";
    readonly RUN_PAUSED: "run.paused";
    readonly RUN_COMPLETED: "run.completed";
    readonly RUN_FAILED: "run.failed";
    readonly RUN_TIMEOUT: "run.timeout";
    readonly RUN_DEAD_LETTERED: "run.dead_lettered";
    readonly PROACTIVE_SURFACING_OUTCOME: "proactive.surfacing.outcome";
    readonly WEBHOOK_TEST: "webhook.test";
};
export type RuntimeEventType = (typeof RUNTIME_EVENT_TYPES)[keyof typeof RUNTIME_EVENT_TYPES];
export declare function isRuntimeEventType(value: unknown): value is RuntimeEventType;
export declare function parseRuntimeEventType(value: unknown): RuntimeEventType | undefined;
export declare function requireRuntimeEventType(value: unknown, context?: string): RuntimeEventType;
