import { type IpcRequestClaimProbe } from '../../../../shared/ipc-interaction-lifetime.js';
import type { SemanticCapabilityDefinition } from '../../../../shared/semantic-capabilities.js';
import type { PermissionDecision } from './types.js';
declare const AGENT_FOLDER_OPTION_KEY: "workspaceFolder";
export declare function requestPermissionApproval(options: {
    appId?: string;
    agentId?: string;
    [AGENT_FOLDER_OPTION_KEY]: string;
    toolName: string;
    title?: string;
    displayName?: string;
    description?: string;
    decisionReason?: string;
    closestRule?: {
        rule: string;
        reason: string;
    };
    blockedPath?: string;
    toolInput?: unknown;
    hostInjectedCommandPrefix?: string;
    toolUseID?: string;
    agentID?: string;
    suggestions?: unknown[];
    decisionOptions?: readonly string[];
    semanticCapabilityDefinitions?: Record<string, SemanticCapabilityDefinition>;
    targetJid?: string;
    threadId?: string;
    signal?: AbortSignal;
    claimProbe?: IpcRequestClaimProbe;
}): Promise<PermissionDecision>;
export {};
