export declare const WORKSPACE_GROUP_DIR: string;
export declare const WORKSPACE_EXTRA_DIR: string;
export declare const IPC_BASE_DIR: string;
export declare const IPC_INPUT_DIR: string;
export declare const IPC_INTERACTION_BOUNDARY_DIR: string;
export declare const IPC_AUTH_TOKEN: string;
export declare const APP_ID: string;
export declare const AGENT_ID: string;
export declare const CHAT_JID: string;
export declare const PROVIDER_ACCOUNT_ID: string;
export declare const JOB_ID: string;
export declare const JOB_NAME: string;
export declare const JOB_RUN_ID: string;
export declare const JOB_RUN_LEASE_TOKEN: string;
export declare const JOB_RUN_LEASE_FENCING_VERSION: string;
export declare const IPC_RESPONSE_VERIFY_KEY: string;
export declare const IPC_RESPONSE_KEY_ID: string;
export declare const PERMISSION_MODE: string;
export declare const PERMISSION_LANE: string;
export declare const TURN_INTENT_SUMMARY: string;
export declare const SENDER_ID: string;
export declare const SENDER_IS_CONTROL_APPROVER: boolean;
export declare const PERMISSION_REQUEST_TIMEOUT_MS: number;
export declare const IPC_INPUT_CLOSE_SENTINEL: string;
export declare const RUNTIME_SIGNAL_FALLBACK_POLL_MS = 500;
export declare function buildEffectiveToolNetworkEnv(toolNetworkEnv?: Record<string, string>): Record<string, string>;
export declare function buildSdkEnv(modelCredentialEnv?: Record<string, string>): Record<string, string | undefined>;
export declare function resolveClaudeCodeExecutableFromPath(envPath?: string | undefined): string | undefined;
export declare function allowedOuterSandboxClaudeExecutable(executable: string | undefined): string | undefined;
export declare function resolveMcpServerPath(importMetaUrl: string): string;
export declare function resolveWorkspaceIpcDir(workspaceFolder: string): string;
export declare function discoverAdditionalDirectories(): string[];
