import { type AdminMcpToolName } from '../../shared/admin-mcp-tools.js';
import { type SemanticCapabilityDefinition } from '../../shared/semantic-capabilities.js';
export declare const IPC_DIR: string;
export declare const MESSAGES_DIR: string;
export declare const TASKS_DIR: string;
export declare const MEMORY_REQUESTS_DIR: string;
export declare const MEMORY_RESPONSES_DIR: string;
export declare const BROWSER_REQUESTS_DIR: string;
export declare const BROWSER_RESPONSES_DIR: string;
export declare const TASK_RESPONSES_DIR: string;
export declare const IPC_AUTH_TOKEN: string;
export declare const BROWSER_IPC_AUTH_TOKEN: string;
export declare const MEMORY_IPC_AUTH_TOKEN: string;
export declare const IPC_RESPONSE_VERIFY_KEY: string;
export declare const IPC_RESPONSE_KEY_ID: string;
export declare const chatJid: string;
export declare const providerAccountId: string | undefined;
export declare const workspaceFolder: string;
export declare const appId: string | undefined;
export declare const agentId: string | undefined;
export declare const jobId: string | undefined;
export declare const permissionLane: string;
export declare const jobRunId: string | undefined;
export declare const jobRunLeaseToken: string | undefined;
export declare const jobRunLeaseFencingVersion: string | undefined;
export declare const threadId: string | undefined;
export declare const memoryUserId: string | undefined;
export declare const memoryDefaultScope: string;
export declare const memoryReviewerIsControlApprover: boolean;
export declare const memoryIpcAllowedActions: import("../../shared/memory-ipc-actions.js").GantryMemoryIpcAction[];
export declare const browserProfileName: string | undefined;
export declare const lockedAccessPreset: boolean;
export declare const deploymentMode: 'workstation' | 'fleet';
export declare const enabledAdminMcpTools: Set<"settings_desired_state" | "request_settings_update" | "guided_action_preview" | "admin_permission_list" | "admin_permission_revoke" | "service_restart" | "register_agent">;
export declare const enabledGantryMcpTools: Set<string>;
export declare const configuredAllowedTools: string[];
export declare const attachedSkillSourceIds: string[];
export declare const selectedSkillDisplays: string[];
export declare const attachedMcpSourceIds: string[];
export declare const availableSemanticCapabilities: SemanticCapabilityDefinition[];
export declare function isAdminMcpToolEnabled(toolName: AdminMcpToolName): boolean;
export declare function currentEnabledAdminMcpTools(): Set<AdminMcpToolName>;
export declare function currentConfiguredAllowedTools(): string[];
export declare function capabilityStatusText(): string;
