import { getDeploymentMode } from '../../config/index.js';
import { type AgentToolRuleSettingsRepositories } from '../../config/settings/agent-tool-rule-settings-mirror.js';
import { logger } from '../../infrastructure/logging/logger.js';
import type { HostnameLookup } from '../../domain/network/public-address-policy.js';
import { writeGroupsSnapshot } from '../../runtime/agent-spawn.js';
import { startIpcWatcher, type IpcDeps } from '../../runtime/ipc.js';
import { recoverPendingMessages } from '../../runtime/message-loop.js';
import { startSchedulerLoop } from '../../jobs/scheduler.js';
import type { RuntimeJobRepository } from '../../domain/repositories/ops-repo.js';
import type { WorkerCoordinationRepository } from '../../domain/ports/worker-coordination.js';
import type { RuntimeDependencyRepository } from '../../domain/ports/fleet-capability-state.js';
import type { LiveAdmissionWakeupSource, LiveTurnCommandWakeupSource, LiveTurnCoordinationRepository } from '../../domain/ports/live-turns.js';
import type { AgentRepository, CapabilitySecretRepository, McpServerRepository, OutboundDeliveryRepository, PermissionRepository, SkillCatalogRepository, ToolCatalogRepository } from '../../domain/ports/repositories.js';
import type { AgentCredentialBroker } from '../../domain/ports/agent-credential-broker.js';
import type { SessionMemoryCollector } from '../../domain/ports/session-memory-collector.js';
import type { SkillArtifactStore } from '../../domain/ports/skill-artifact-store.js';
import type { RemoteMcpDnsValidationCache } from '../../application/mcp/mcp-server-policy.js';
import type { ChannelWiring } from './channel-wiring-types.js';
import type { RuntimeApp, RuntimeAppRepository } from './runtime-app.js';
import { startOutboundDeliveryRecoveryLoop } from '../../jobs/outbound-delivery-recovery.js';
import { type RecoveryCoordinatorPort } from './live-execution.js';
import type { ProcessRole } from './roles/process-role.js';
export { stopAsyncTaskRecoveryLoop } from './runtime-services-async-task-recovery.js';
type RuntimeBootstrapRepository = RuntimeAppRepository & RuntimeJobRepository;
type LiveTurnCommandWakeupSourceFactory = () => LiveTurnCommandWakeupSource | undefined;
type RuntimeDependencyRepositoryFactory = () => RuntimeDependencyRepository | undefined;
type RuntimeStorageDep = 'getAsyncTaskRepository' | 'getFileArtifactStore' | 'getPermissionPromotionRepository' | 'getPermissionDecisionMemoryRepository';
interface Deps extends Pick<IpcDeps, RuntimeStorageDep> {
    startSchedulerLoop: typeof startSchedulerLoop;
    startIpcWatcher: typeof startIpcWatcher;
    writeGroupsSnapshot: typeof writeGroupsSnapshot;
    opsRepository: RuntimeBootstrapRepository;
    recoverPendingMessages: typeof recoverPendingMessages;
    logger: Pick<typeof logger, 'info' | 'warn' | 'fatal'>;
    mcpHostnameLookup?: HostnameLookup;
    collectSessionMemory: SessionMemoryCollector;
    getCredentialBroker?: () => Promise<AgentCredentialBroker | undefined>;
    getAgentRepository?: () => AgentRepository | undefined;
    getSkillRepository?: () => SkillCatalogRepository | undefined;
    getMcpServerRepository?: () => McpServerRepository | undefined;
    getCapabilitySecretRepository?: () => CapabilitySecretRepository | undefined;
    runApprovedCommand?: IpcDeps['runApprovedCommand'];
    getMcpDnsValidationCache?: () => RemoteMcpDnsValidationCache | undefined;
    getSkillArtifactStore?: () => SkillArtifactStore | undefined;
    getToolRepository: () => ToolCatalogRepository;
    getPermissionRepository?: () => PermissionRepository;
    settingsRepositories?: AgentToolRuleSettingsRepositories;
    getOutboundDeliveryRepository?: () => OutboundDeliveryRepository | undefined;
    getWorkerCoordinationRepository?: () => WorkerCoordinationRepository | undefined;
    getLiveTurnRepository?: () => LiveTurnCoordinationRepository | undefined;
    getLiveAdmissionWakeupSource?: () => LiveAdmissionWakeupSource | undefined;
    getLiveTurnCommandWakeupSource?: LiveTurnCommandWakeupSourceFactory;
    getRuntimeDependencyRepository?: RuntimeDependencyRepositoryFactory;
    getDeploymentMode: typeof getDeploymentMode;
    startOutboundDeliveryRecoveryLoop: typeof startOutboundDeliveryRecoveryLoop;
    callBrowserTool: IpcDeps['callBrowserTool'];
    publishRuntimeEvent: IpcDeps['publishRuntimeEvent'];
    subscribeRuntimeEvents: IpcDeps['subscribeRuntimeEvents'];
    publishBrowserJobActivity: IpcDeps['publishBrowserJobActivity'];
    closeBrowserToolBackends: IpcDeps['closeBrowserToolBackends'];
    executionAdapter?: RuntimeApp['executionAdapter'];
    executionAdapters?: RuntimeApp['executionAdapters'];
    runnerSandboxProvider: RuntimeApp['runnerSandboxProvider'];
    exit: (code: number) => never;
}
type RuntimeServicesDefaults = Omit<Deps, 'opsRepository' | 'getToolRepository' | 'getPermissionRepository' | 'getWorkerCoordinationRepository' | 'getLiveTurnRepository' | 'runnerSandboxProvider'>;
export type RuntimeServicesOptions = {
    app: RuntimeApp;
    channelWiring: ChannelWiring;
    liveTurnsEnabled?: boolean;
    recoveryCoordinator?: RecoveryCoordinatorPort;
    processRole?: ProcessRole;
    liveExecution?: boolean;
    jobExecution?: boolean;
};
export declare function getOldestWaitingLiveAdmissionSeconds(): number;
export declare function stopLiveTurnRecoveryLoop(): void;
export declare function stopLiveAdmissionLoop(timeoutMs?: number): Promise<void>;
export declare function beginDrainingLiveTurnAdmission(): void;
export declare function shutdownLiveTurnAuthority(): Promise<void>;
export declare function startRuntimeServices(options: RuntimeServicesOptions, deps: Partial<RuntimeServicesDefaults> & Pick<Deps, 'opsRepository' | 'getToolRepository'> & Partial<Pick<Deps, 'getPermissionRepository' | 'getWorkerCoordinationRepository' | 'getLiveTurnRepository' | 'getLiveTurnCommandWakeupSource'>>): Promise<void>;
