import { randomBytes } from 'crypto';

import { Pool } from 'pg';

import {
  parsePostgresConnectionUrl,
  validatePostgresConnectionUrl,
} from '../../../storage/postgres/url.js';
import { quotePostgresIdentifier } from '../../../storage/postgres/storage-service.js';
import { redactString } from '../../../../infrastructure/logging/logger.js';

export const ONECLI_DATABASE_URL_ENV = 'ONECLI_DATABASE_URL';
export const ONECLI_SECRET_ENCRYPTION_KEY_ENV = 'SECRET_ENCRYPTION_KEY';
export const ONECLI_DEFAULT_SCHEMA = 'onecli';
export const ONECLI_SECRET_ENCRYPTION_KEY_BYTES = 32;

export interface OnecliPersistenceReadiness {
  status: 'pass' | 'warn' | 'fail';
  message: string;
  details?: string[];
  nextAction?: string;
}

export interface PostgresDatabaseIdentity {
  hostname: string;
  port: string;
  database: string;
}

export function generateOnecliSecretEncryptionKey(): string {
  return randomBytes(ONECLI_SECRET_ENCRYPTION_KEY_BYTES).toString('base64');
}

function estimateShannonEntropyPerChar(value: string): number {
  const counts = new Map<string, number>();
  for (const char of value) {
    counts.set(char, (counts.get(char) || 0) + 1);
  }
  let entropy = 0;
  for (const count of counts.values()) {
    const probability = count / value.length;
    entropy -= probability * Math.log2(probability);
  }
  return entropy;
}

export function validateOnecliSecretEncryptionKey(
  secret: string | undefined,
): { ok: true } | { ok: false; message: string; nextAction: string } {
  const trimmed = secret?.trim() || '';
  if (!trimmed) {
    return {
      ok: false,
      message:
        'SECRET_ENCRYPTION_KEY is required for stateless OneCLI restarts.',
      nextAction:
        'Set SECRET_ENCRYPTION_KEY in the runtime .env, or rerun `myclaw local setup` to generate one.',
    };
  }
  if (
    !/^[A-Za-z0-9+/]+={0,2}$/.test(trimmed) ||
    Buffer.from(trimmed, 'base64').length !==
      ONECLI_SECRET_ENCRYPTION_KEY_BYTES ||
    /^([A-Za-z0-9+/=])\1+$/.test(trimmed) ||
    estimateShannonEntropyPerChar(trimmed) < 4.2
  ) {
    return {
      ok: false,
      message:
        'SECRET_ENCRYPTION_KEY must be a generated base64-encoded 32-byte secret for broker credential encryption.',
      nextAction:
        'Replace SECRET_ENCRYPTION_KEY with a value generated by `myclaw local setup` or `openssl rand -base64 32`, then restart OneCLI.',
    };
  }
  return { ok: true };
}

function validateOnecliSchemaName(schema: string): void {
  if (!/^[a-z_][a-z0-9_]{0,62}$/.test(schema)) {
    throw new Error(
      'OneCLI schema must be a lowercase PostgreSQL identifier (letters, numbers, and underscores).',
    );
  }
}

export function getPostgresDatabaseIdentity(
  postgresUrl: string,
): PostgresDatabaseIdentity {
  const parsed = parsePostgresConnectionUrl(postgresUrl);
  const database = decodeURIComponent(parsed.pathname.replace(/^\/+/, ''));
  return {
    hostname: parsed.hostname.toLowerCase(),
    port: parsed.port || '5432',
    database,
  };
}

export function validateSharedPostgresDatabase(input: {
  myclawPostgresUrl: string;
  onecliPostgresUrl: string;
}): { ok: true } | { ok: false; message: string; nextAction: string } {
  try {
    const myclaw = getPostgresDatabaseIdentity(input.myclawPostgresUrl);
    const onecli = getPostgresDatabaseIdentity(input.onecliPostgresUrl);
    if (
      myclaw.hostname === onecli.hostname &&
      myclaw.port === onecli.port &&
      myclaw.database === onecli.database
    ) {
      return { ok: true };
    }
    return {
      ok: false,
      message:
        'MYCLAW_DATABASE_URL and ONECLI_DATABASE_URL must point to the same Postgres database.',
      nextAction:
        'Use one database with separate schemas and separate database users for MyClaw and OneCLI.',
    };
  } catch (err) {
    return {
      ok: false,
      message: err instanceof Error ? err.message : String(err),
      nextAction:
        'Set MYCLAW_DATABASE_URL and ONECLI_DATABASE_URL to valid PostgreSQL URLs for the same database.',
    };
  }
}

export function renderOnecliDatabaseUrl(input: {
  postgresUrl: string;
  schema?: string;
}): string {
  const schema = input.schema || ONECLI_DEFAULT_SCHEMA;
  validateOnecliSchemaName(schema);
  const parsed = new URL(input.postgresUrl);
  parsed.searchParams.delete('options');
  parsed.searchParams.set('schema', schema);
  return parsed.toString();
}

export function extractOnecliDatabaseSchema(postgresUrl: string): string {
  try {
    const parsed = new URL(postgresUrl);
    return parsed.searchParams.get('schema') || '';
  } catch {
    return '';
  }
}

export function validateOnecliDatabaseUrl(input: {
  postgresUrl: string;
  schema: string;
}): { ok: true } | { ok: false; message: string; nextAction: string } {
  try {
    validateOnecliSchemaName(input.schema);
  } catch (err) {
    return {
      ok: false,
      message: err instanceof Error ? err.message : String(err),
      nextAction: 'Use a simple schema name such as onecli.',
    };
  }
  try {
    validatePostgresConnectionUrl(input.postgresUrl, {
      allowLocalhost: true,
    });
  } catch (err) {
    return {
      ok: false,
      message: err instanceof Error ? err.message : String(err),
      nextAction: 'Set ONECLI_DATABASE_URL to a valid PostgreSQL URL.',
    };
  }
  const schema = extractOnecliDatabaseSchema(input.postgresUrl);
  if (schema !== input.schema) {
    return {
      ok: false,
      message: `ONECLI_DATABASE_URL must set schema=${input.schema}`,
      nextAction: `Set ONECLI_DATABASE_URL to the shared Postgres URL with schema=${input.schema}.`,
    };
  }
  return { ok: true };
}

export async function inspectOnecliPersistenceReadiness(input: {
  postgresUrl: string;
  schema: string;
  secretEncryptionKey?: string;
  myclawPostgresUrl?: string;
  myclawSchema?: string;
}): Promise<OnecliPersistenceReadiness> {
  if (!input.postgresUrl.trim()) {
    return {
      status: 'fail',
      message: 'ONECLI_DATABASE_URL is required for OneCLI persistence.',
      nextAction:
        'Run `myclaw local setup` or configure ONECLI_DATABASE_URL to use the shared Postgres database with schema=onecli.',
    };
  }
  const validation = validateOnecliDatabaseUrl({
    postgresUrl: input.postgresUrl,
    schema: input.schema,
  });
  if (!validation.ok) {
    return {
      status: 'fail',
      message: 'OneCLI database URL is not schema-isolated.',
      details: [redactString(validation.message)],
      nextAction: validation.nextAction,
    };
  }
  const secretValidation = validateOnecliSecretEncryptionKey(
    input.secretEncryptionKey,
  );
  if (!secretValidation.ok) {
    return {
      status: 'fail',
      message: secretValidation.message,
      nextAction: secretValidation.nextAction,
    };
  }
  if (input.myclawPostgresUrl?.trim()) {
    const sharedDatabase = validateSharedPostgresDatabase({
      myclawPostgresUrl: input.myclawPostgresUrl,
      onecliPostgresUrl: input.postgresUrl,
    });
    if (!sharedDatabase.ok) {
      return {
        status: 'fail',
        message: sharedDatabase.message,
        nextAction: sharedDatabase.nextAction,
      };
    }
    const onecliUser = new URL(input.postgresUrl).username;
    const myclawUser = new URL(input.myclawPostgresUrl).username;
    if (onecliUser && myclawUser && onecliUser === myclawUser) {
      return {
        status: 'fail',
        message:
          'OneCLI and MyClaw database URLs must use different Postgres roles.',
        nextAction:
          'Use one database with separate schemas and separate database users for MyClaw and OneCLI.',
      };
    }
  }

  const pool = new Pool({ connectionString: input.postgresUrl });
  try {
    const currentUser = await pool.query<{ current_user: string }>(
      'SELECT current_user',
    );
    const currentUserName = currentUser.rows[0]?.current_user || '';
    const schema = await pool.query<{ exists: boolean }>(
      `SELECT EXISTS (
        SELECT 1 FROM information_schema.schemata WHERE schema_name = $1
      ) AS exists`,
      [input.schema],
    );
    if (!schema.rows[0]?.exists) {
      return {
        status: 'fail',
        message: `OneCLI schema "${input.schema}" does not exist.`,
        nextAction:
          'Run `myclaw local setup` or create the OneCLI schema before starting the broker.',
      };
    }
    const currentSchema = await pool.query<{ current_schema: string | null }>(
      'SELECT current_schema() AS current_schema',
    );
    if (currentSchema.rows[0]?.current_schema !== input.schema) {
      return {
        status: 'fail',
        message:
          'OneCLI database role search_path does not resolve to the configured schema.',
        details: [
          `current_schema=${currentSchema.rows[0]?.current_schema || 'none'}`,
          `expected_schema=${input.schema}`,
        ],
        nextAction: `Set the OneCLI database role search_path to ${input.schema}, public and restart OneCLI.`,
      };
    }
    if (input.myclawSchema?.trim()) {
      const myclawUsage = await pool.query<{ has_access: boolean }>(
        'SELECT has_schema_privilege(current_user, $1, $2) AS has_access',
        [input.myclawSchema, 'USAGE'],
      );
      const myclawCreate = await pool.query<{ has_access: boolean }>(
        'SELECT has_schema_privilege(current_user, $1, $2) AS has_access',
        [input.myclawSchema, 'CREATE'],
      );
      if (myclawUsage.rows[0]?.has_access || myclawCreate.rows[0]?.has_access) {
        return {
          status: 'fail',
          message: 'OneCLI database role can access the MyClaw runtime schema.',
          details: [`current_user=${currentUserName}`],
          nextAction:
            'Revoke MyClaw schema privileges from the OneCLI database role and rerun doctor.',
        };
      }
    }
    if (input.myclawPostgresUrl?.trim()) {
      const reciprocalPool = new Pool({
        connectionString: input.myclawPostgresUrl,
      });
      try {
        const reciprocalUser = await reciprocalPool.query<{
          current_user: string;
        }>('SELECT current_user');
        const reciprocalUserName = reciprocalUser.rows[0]?.current_user || '';
        const onecliUsage = await reciprocalPool.query<{
          has_access: boolean;
        }>('SELECT has_schema_privilege(current_user, $1, $2) AS has_access', [
          input.schema,
          'USAGE',
        ]);
        const onecliCreate = await reciprocalPool.query<{
          has_access: boolean;
        }>('SELECT has_schema_privilege(current_user, $1, $2) AS has_access', [
          input.schema,
          'CREATE',
        ]);
        if (
          onecliUsage.rows[0]?.has_access ||
          onecliCreate.rows[0]?.has_access
        ) {
          return {
            status: 'fail',
            message:
              'MyClaw database role can access the OneCLI broker schema.',
            details: [`current_user=${reciprocalUserName}`],
            nextAction:
              'Revoke OneCLI schema privileges from the MyClaw database role and rerun doctor.',
          };
        }
      } finally {
        await reciprocalPool.end().catch(() => undefined);
      }
    }
    const publicTables = await pool.query<{ table_name: string }>(
      `SELECT table_name
       FROM information_schema.tables
       WHERE table_schema = 'public'
         AND table_type = 'BASE TABLE'
       ORDER BY table_name
       LIMIT 5`,
    );
    if (publicTables.rows.length > 0) {
      return {
        status: 'fail',
        message:
          'Public schema contains application tables; OneCLI must be isolated in its configured schema.',
        details: publicTables.rows.map((row) => `public.${row.table_name}`),
        nextAction: `Point OneCLI at ONECLI_DATABASE_URL with schema=${input.schema} and move or remove public application tables.`,
      };
    }

    return {
      status: 'pass',
      message: `OneCLI persistence is configured for schema "${input.schema}" as role "${currentUserName}".`,
    };
  } catch (err) {
    return {
      status: 'fail',
      message: 'Could not verify OneCLI persistence readiness.',
      details: [redactString(err instanceof Error ? err.message : String(err))],
      nextAction:
        'Verify ONECLI_DATABASE_URL credentials, network access, and schema permissions.',
    };
  } finally {
    await pool.end().catch(() => undefined);
  }
}

export function renderCreateSchemaSql(schema: string): string {
  return `CREATE SCHEMA IF NOT EXISTS ${quotePostgresIdentifier(schema)};`;
}
