import '../../channels/register-builtins.js';
import { type SenderControlAllowlistConfig } from './control-allowlist.js';
import { type SenderAllowlistConfig } from './sender-allowlist.js';
import type { RuntimeCredentialBrokerSettings, RuntimeAgentSettings, RuntimeMemoryBackfillSettings, RuntimeMemoryLlmModels, RuntimeMemorySettings, RuntimePermissionSettings, RuntimeSandboxSettings, RuntimeSettings, RuntimeStorageSettings } from './runtime-settings-types.js';
export { DEFAULT_AGENT_NAME } from '../../shared/default-agent.js';
export declare const DEFAULT_STORAGE_POSTGRES_URL_ENV = "GANTRY_DATABASE_URL";
export declare const DEFAULT_STORAGE_POSTGRES_SCHEMA = "gantry";
export declare const DEFAULT_MODEL_GATEWAY_BIND_HOST = "127.0.0.1";
export declare const DEFAULT_EMBED_MODEL = "text-embedding-3-small";
export declare const DEFAULT_EMBED_DIMENSIONS = 1536;
export declare const DEFAULT_OPENAI_DAILY_EMBED_LIMIT = 500;
export declare const DEFAULT_MEMORY_EXTRACTOR_MAX_FACTS = 8;
export declare const DEFAULT_MEMORY_EXTRACTOR_MIN_CONFIDENCE = 0.6;
export declare const DEFAULT_MEMORY_DREAMING_CRON = "15 3 * * *";
export declare const DEFAULT_MEMORY_DREAMING_ALERTS = false;
export declare const DEFAULT_MEMORY_EMBED_BATCH_SIZE = 16;
export declare const DEFAULT_MEMORY_MAINTENANCE_MAX_PENDING = 5000;
export declare const DEFAULT_MEMORY_BACKFILL_ENABLED = true;
export declare const DEFAULT_MEMORY_BACKFILL_CRON = "45 3 * * *";
export declare const DEFAULT_MEMORY_BACKFILL_MAX_ITEMS_PER_RUN = 500;
export declare const DEFAULT_MEMORY_BACKFILL_MODE = "auto";
export declare const DEFAULT_MEMORY_BACKFILL_PROVIDER_BATCH_MIN_ITEMS = 100;
export declare const DEFAULT_AGENT_SESSION_MEMORY_ITEM_LIMIT = 8;
export declare const DEFAULT_AGENT_SESSION_MAX_MEMORY_CONTEXT_CHARS = 12000;
export declare const DEFAULT_BROWSER_USAGE_ENABLED = false;
export declare const DEFAULT_BROWSER_USAGE_MODE = "audit";
export declare const DEFAULT_BROWSER_USAGE_WINDOW_MS = 60000;
export declare const DEFAULT_BROWSER_USAGE_MAX_ACTIONS_PER_WINDOW = 120;
export declare const DEFAULT_BROWSER_USAGE_MAX_CONCURRENT_PER_SITE = 1;
export declare const DEFAULT_RUNTIME_SANDBOX_PROVIDER = "direct";
export declare const DEFAULT_RUNTIME_DEPLOYMENT_MODE = "workstation";
export declare const DEFAULT_LLM_GLOBAL_MAX_IN_FLIGHT = 32;
export declare const DEFAULT_LLM_PER_APP_KEY_MAX_IN_FLIGHT = 8;
export declare const DEFAULT_LIVE_ADMISSION_BACKLOG = 100;
export declare function getDefaultRuntimeSandboxSettings(): RuntimeSandboxSettings;
export declare function getDefaultMemoryBackfillSettings(): RuntimeMemoryBackfillSettings;
export declare function getProviderManagedMemoryDefaults(providerId?: string): RuntimeMemoryLlmModels;
export declare function createDefaultRuntimeSettings(): RuntimeSettings;
export declare function applyProviderManagedMemoryDefaults(settings: RuntimeSettings, providerId?: string): void;
export declare function applyModelDefaults(settings: RuntimeSettings, chatAlias: string): void;
export type { SenderAllowlistConfig, SenderControlAllowlistConfig, RuntimeCredentialBrokerSettings, RuntimeAgentSettings, RuntimeMemoryLlmModels, RuntimeMemorySettings, RuntimePermissionSettings, RuntimeSettings, RuntimeStorageSettings, };
