import type { JsonSchema } from './openapi-route-helpers.js';
import {
  peopleOpenApiRequestSchemas,
  peopleOpenApiResponseSchemas,
} from './openapi-people.js';

const ref = (name: string): JsonSchema => ({
  $ref: `#/components/schemas/${name}`,
});

export const openApiResponseSchemas: Record<string, JsonSchema> = {
  getBrowserOnboardingStatus: {
    type: 'object',
    required: ['completed', 'deployment'],
    properties: {
      completed: { type: 'boolean' },
      deployment: {
        oneOf: [
          {
            type: 'object',
            properties: {
              modelCandidate: {
                oneOf: [
                  {
                    type: 'object',
                    required: [
                      'id',
                      'providerId',
                      'authMode',
                      'state',
                      'modelAlias',
                      'expiresAt',
                      'verificationExpiresAt',
                    ],
                  },
                  { type: 'null' },
                ],
              },
            },
          },
          { type: 'null' },
        ],
      },
    },
  },
  stageBrowserOnboardingModelCandidate: {
    type: 'object',
    required: ['candidate'],
  },
  checkBrowserOnboardingModelCandidate: {
    type: 'object',
    required: ['candidate'],
  },
  listBrowserOnboardingCandidateModels: {
    type: 'object',
    required: ['models'],
    properties: {
      models: {
        type: 'array',
        items: {
          type: 'object',
          required: ['alias', 'displayName', 'providerId'],
          properties: {
            alias: { type: 'string' },
            displayName: { type: 'string' },
            providerId: { type: 'string' },
          },
        },
      },
    },
  },
  verifyBrowserOnboardingModelCandidate: {
    type: 'object',
    required: ['candidate'],
  },
  activateBrowserOnboardingModelCandidate: { type: 'object' },
  cancelBrowserOnboardingModelCandidate: { type: 'object' },
  stageBrowserOnboardingProviderCandidate: {
    type: 'object',
    required: ['candidate'],
  },
  validateBrowserOnboardingProviderCandidate: { type: 'object' },
  activateBrowserOnboardingProviderCandidate: { type: 'object' },
  cancelBrowserOnboardingProviderCandidate: { type: 'object' },
  discoverBrowserOnboardingConversations: {
    type: 'object',
    required: ['conversations', 'nextCursor'],
  },
  listBrowserOnboardingConversationMembers: {
    type: 'object',
    required: ['members'],
    properties: {
      members: {
        type: 'array',
        items: {
          type: 'object',
          required: ['id', 'displayName'],
          properties: {
            id: { type: 'string' },
            displayName: { type: 'string' },
          },
        },
      },
    },
  },
  joinBrowserOnboardingConversation: {
    type: 'object',
    required: ['joined'],
    properties: { joined: { type: 'boolean', const: true } },
  },
  bindBrowserOnboardingAssignment: { type: 'object', required: ['assignment'] },
  getBrowserOnboardingChallenge: { type: 'object', required: ['challenge'] },
  createBrowserOnboardingChallenge: { type: 'object', required: ['challenge'] },
  completeBrowserOnboarding: {
    type: 'object',
    required: ['completed'],
    properties: { completed: { type: 'boolean', const: true } },
  },
  getBrowserAgentWorkflowMap: {
    type: 'object',
    required: ['relationships'],
    properties: {
      relationships: {
        type: 'array',
        items: { type: 'object', required: ['id', 'kind'] },
      },
    },
  },
  getBrowserOnboardingChannelManifest: {
    type: 'object',
    required: ['manifestJson', 'createUrl', 'permissionGroups'],
    properties: {
      manifestJson: { type: 'string' },
      createUrl: { type: 'string', format: 'uri' },
      permissionGroups: { type: 'array', items: { type: 'object' } },
    },
  },
  bindMcpServerToAgent: ref('AgentMcpServerBindingResponse'),
  bindSkillToAgent: ref('AgentSkillBindingResponse'),
  connectMcpServer: ref('McpServerResponse'),
  createAgent: ref('Agent'),
  createExternalIngress: ref('ExternalIngress'),
  createJob: ref('JobCreateResponse'),
  createMemory: ref('MemoryItemResponse'),
  createProviderAccount: ref('ProviderAccount'),
  createWebhook: ref('Webhook'),
  deleteExternalIngress: ref('DeleteResponse'),
  deleteJob: ref('DeleteResponse'),
  deleteMemory: ref('DeleteResponse'),
  deleteWebhook: ref('DeleteResponse'),
  disableConversationInstall: ref('ConversationInstallDeleteResponse'),
  disableMcpServer: ref('McpServerResponse'),
  disableProviderAccount: ref('ProviderAccountDeleteResponse'),
  discoverProviderConversations: ref('ConversationListResponse'),
  enableConversationInstall: ref('ConversationInstall'),
  ensureSession: ref('SessionEnsureResponse'),
  getAgent: ref('Agent'),
  getAgentAdminSummary: ref('AgentAdminSummaryResponse'),
  getAgentDelegates: ref('AgentDelegatesResponse'),
  getAgentAccess: ref('AgentAccessResponse'),
  listAgentProfileFiles: ref('AgentProfileFilesResponse'),
  getAgentProfileFile: ref('AgentProfileFileContentResponse'),
  setAgentProfileFile: ref('AgentProfileFileContentResponse'),
  getCapability: ref('CapabilityManifest'),
  getConversation: ref('Conversation'),
  getDoctor: ref('DoctorResponse'),
  getExternalIngress: ref('ExternalIngress'),
  getHealth: ref('HealthResponse'),
  getJob: ref('Job'),
  getMemoryDreamingStatus: ref('MemoryDreamingStatusResponse'),
  getObserverStatus: ref('ObserverStatusResponse'),
  getMcpServer: ref('McpServerResponse'),
  getModelDefaults: ref('ModelDefaultsResponse'),
  previewGuidedAction: ref('GuidedActionPreview'),
  executeGuidedAction: ref('GuidedActionResult'),
  getProviderAccount: ref('ProviderAccount'),
  getRun: ref('Run'),
  getSession: ref('SessionDetails'),
  getSettings: ref('SettingsResponse'),
  getStatus: ref('ControlStatusResponse'),
  getSkillFile: ref('SkillFileResponse'),
  invokeExternalIngress: ref('ExternalIngressInvokeResponse'),
  invokeLlmChatCompletions: ref('LlmChatCompletionsResponse'),
  invokeLlmMessages: ref('LlmMessagesResponse'),
  invokeLlmMessagesCountTokens: ref('LlmMessagesCountTokensResponse'),
  listConversationInstalls: ref('ConversationInstallListResponse'),
  listAgentMcpServerBindings: ref('AgentMcpServerBindingListResponse'),
  listAgentSkillBindings: ref('AgentSkillBindingListResponse'),
  listAgents: ref('AgentListResponse'),
  getInventory: ref('InventoryResponse'),
  listCapabilities: ref('CapabilityListResponse'),
  listConversationApprovers: ref('ConversationApproversResponse'),
  listConversationMessages: ref('ConversationMessageListResponse'),
  listConversationThreads: ref('ConversationThreadListResponse'),
  listConversations: ref('ConversationListResponse'),
  listExternalIngresses: ref('ExternalIngressListResponse'),
  listJobEvents: ref('JobEventListResponse'),
  listJobs: ref('JobListResponse'),
  listMcpServers: ref('McpServerPageResponse'),
  listMemory: ref('MemoryListResponse'),
  listMemoryReviews: ref('MemoryReviewPageResponse'),
  getMemoryReview: ref('MemoryReviewDetailResponse'),
  decideMemoryReview: ref('MemoryReviewDetailResponse'),
  listObserverInsights: ref('ObserverInsightListResponse'),
  previewObserverDigest: ref('ObserverDigestPreviewResponse'),
  listObserverDeliveries: ref('ObserverDigestDeliveryListResponse'),
  listModelCredentials: ref('ModelCredentialListResponse'),
  listModels: ref('ModelListResponse'),
  listOrStreamSessionEvents: ref('SessionRuntimeEventListResponse'),
  listProviderAccounts: ref('ProviderAccountListResponse'),
  listProviders: ref('ProviderListResponse'),
  listRunEvents: ref('RuntimeEventListResponse'),
  listRuns: ref('RunListResponse'),
  listSessionInteractions: ref('SessionInteractionListResponse'),
  listSessionMessages: ref('SessionMessageListResponse'),
  listSessionRuns: ref('RunListResponse'),
  respondSessionInteraction: ref('SessionInteractionRespondResponse'),
  listSkillFiles: ref('SkillFilesResponse'),
  listSkills: ref('SkillListResponse'),
  listWebhooks: ref('WebhookListResponse'),
  patchMemory: ref('MemoryItemResponse'),
  patchModelCredential: ref('ModelCredentialMutationResponse'),
  patchModelDefaults: ref('ModelDefaultsResponse'),
  patchSettingsReadOnly: ref('ErrorEnvelope'),
  putModelCredential: ref('ModelCredentialMutationResponse'),
  disableModelCredential: ref('ModelCredentialMutationResponse'),
  previewModelSelection: ref('ModelPreviewResponse'),
  pauseJob: ref('JobPauseResponse'),
  purgeWebhookDeadLetters: ref('CountResponse'),
  replayWebhookDeadLetters: ref('CountResponse'),
  replaceAgentAccess: ref('AgentAccessResponse'),
  replaceAgentDelegates: ref('SettingsRevisionResponse'),
  replaceConversationApprovers: ref('ConversationApproversResponse'),
  resumeJob: ref('JobResumeResponse'),
  rotateExternalIngressSecret: ref('ExternalIngress'),
  searchMemory: ref('MemorySearchResponse'),
  sendSessionMessage: ref('SendSessionMessageResponse'),
  testMcpServer: ref('McpServerTestResponse'),
  testWebhook: ref('WebhookTestResponse'),
  triggerJob: ref('JobTriggerResponse'),
  triggerMemoryDreaming: ref('MemoryDreamingResponse'),
  queryUsage: ref('UsageQueryResponse'),
  unbindMcpServerFromAgent: ref('AgentMcpServerBindingResponse'),
  unbindSkillFromAgent: ref('AgentSkillBindingResponse'),
  updateAgent: ref('Agent'),
  updateConversationInstall: ref('ConversationInstall'),
  updateAgentMcpServerBinding: ref('AgentMcpServerBindingResponse'),
  updateExternalIngress: ref('ExternalIngress'),
  updateJob: ref('Job'),
  updateProviderAccount: ref('ProviderAccount'),
  updateWebhook: ref('Webhook'),
  installSkill: ref('SkillResponse'),
  waitForExternalIngress: ref('ExternalIngressInvokeResponse'),
  waitForSessionEvent: ref('SessionWaitEventResponse'),
  waitForTrigger: ref('TriggerWaitResponse'),
  importBrainPages: ref('BrainImportResponse'),
  getBrainStatus: ref('BrainStatusResponse'),
  ...peopleOpenApiResponseSchemas,
};

export const openApiRequestSchemas: Record<string, JsonSchema> = {
  stageBrowserOnboardingModelCandidate: {
    type: 'object',
    required: ['providerId', 'credentials'],
    properties: {
      providerId: { type: 'string' },
      authMode: { type: 'string' },
      credentials: { type: 'object', additionalProperties: true },
    },
    additionalProperties: false,
  },
  checkBrowserOnboardingModelCandidate: {
    type: 'object',
    additionalProperties: false,
  },
  verifyBrowserOnboardingModelCandidate: {
    type: 'object',
    required: ['modelAlias'],
    properties: { modelAlias: { type: 'string' } },
    additionalProperties: false,
  },
  activateBrowserOnboardingModelCandidate: {
    type: 'object',
    required: ['name', 'title'],
    properties: {
      name: { type: 'string' },
      title: { type: 'string' },
      responsibilities: { type: 'string' },
    },
    additionalProperties: false,
  },
  cancelBrowserOnboardingModelCandidate: {
    type: 'object',
    additionalProperties: false,
  },
  bindMcpServerToAgent: ref('AgentMcpServerBindingRequest'),
  bindSkillToAgent: ref('AgentSkillBindingRequest'),
  connectMcpServer: ref('McpServerRequest'),
  createAgent: ref('AgentCreateRequest'),
  createExternalIngress: ref('ExternalIngressRequest'),
  createJob: ref('JobCreateRequest'),
  createMemory: ref('MemorySaveRequest'),
  decideMemoryReview: ref('MemoryReviewDecisionRequest'),
  createProviderAccount: ref('ProviderAccountRequest'),
  createWebhook: ref('WebhookCreateRequest'),
  disableMcpServer: ref('DisableMcpServerRequest'),
  discoverProviderConversations: ref('DiscoverProviderConversationsRequest'),
  enableConversationInstall: ref('ConversationInstallRequest'),
  ensureSession: ref('SessionEnsureRequest'),
  invokeExternalIngress: ref('ExternalIngressInvokeRequest'),
  invokeLlmChatCompletions: ref('LlmChatCompletionsRequest'),
  invokeLlmMessages: ref('LlmMessagesRequest'),
  ...peopleOpenApiRequestSchemas,
  invokeLlmMessagesCountTokens: ref('LlmMessagesCountTokensRequest'),
  importBrainPages: ref('BrainImportRequest'),
  patchMemory: ref('MemorySaveRequest'),
  patchModelCredential: ref('ModelCredentialPatchRequest'),
  patchModelDefaults: ref('ModelDefaultsPatchRequest'),
  putModelCredential: ref('ModelCredentialWriteRequest'),
  previewModelSelection: ref('ModelPreviewRequest'),
  previewGuidedAction: ref('GuidedActionRequest'),
  executeGuidedAction: ref('GuidedActionRequest'),
  patchSettingsReadOnly: ref('ReadOnlySettingsPatchRequest'),
  replaceAgentAccess: ref('AgentAccessRequest'),
  replaceAgentDelegates: ref('ReplaceAgentDelegatesRequest'),
  setAgentProfileFile: ref('PutAgentProfileFileRequest'),
  replaceConversationApprovers: ref('ConversationApproversRequest'),
  respondSessionInteraction: ref('SessionInteractionRespondRequest'),
  searchMemory: ref('MemorySearchRequest'),
  sendSessionMessage: ref('SendSessionMessageRequest'),
  testMcpServer: ref('McpServerTestRequest'),
  triggerMemoryDreaming: ref('MemoryDreamingTriggerRequest'),
  updateAgent: ref('AgentUpdateRequest'),
  updateConversationInstall: ref('ConversationInstallRequest'),
  updateAgentMcpServerBinding: ref('AgentMcpServerBindingRequest'),
  updateExternalIngress: ref('ExternalIngressRequest'),
  updateJob: ref('JobUpdateRequest'),
  updateProviderAccount: ref('ProviderAccountUpdateRequest'),
  updateWebhook: ref('WebhookUpdateRequest'),
  waitForExternalIngress: ref('ExternalIngressInvokeRequest'),
};
