import { doc, ids, query, type RouteDoc } from './openapi-route-helpers.js';

export const extendedOpenApiRouteDocs: RouteDoc[] = [
  doc(
    'get',
    '/v1/jobs',
    'listJobs',
    'Jobs',
    'List jobs',
    'Lists jobs visible to the API key app scope.',
    ['jobs:read'],
  ),
  doc(
    'post',
    '/v1/jobs',
    'createJob',
    'Jobs',
    'Create a job',
    'Creates or dry-runs a job using catalog-resolved models.',
    ['jobs:write'],
    { body: 'json', status: '201' },
  ),
  doc(
    'get',
    '/v1/jobs/{jobId}',
    'getJob',
    'Jobs',
    'Get job',
    'Reads a job with runtime visibility metadata.',
    ['jobs:read'],
    { parameters: [ids.job] },
  ),
  doc(
    'patch',
    '/v1/jobs/{jobId}',
    'updateJob',
    'Jobs',
    'Update job',
    'Updates job prompt, context, routes, capabilities, status, or model.',
    ['jobs:write'],
    { body: 'json', parameters: [ids.job] },
  ),
  doc(
    'delete',
    '/v1/jobs/{jobId}',
    'deleteJob',
    'Jobs',
    'Delete job',
    'Deletes a job owned by the API key app scope.',
    ['jobs:write'],
    { body: 'none', parameters: [ids.job] },
  ),
  doc(
    'get',
    '/v1/jobs/{jobId}/events',
    'listJobEvents',
    'Jobs',
    'List job events',
    'Lists persisted runtime events for a job.',
    ['jobs:read'],
    { parameters: [ids.job] },
  ),
  doc(
    'post',
    '/v1/jobs/{jobId}/pause',
    'pauseJob',
    'Jobs',
    'Pause job',
    'Pauses future execution for a job.',
    ['jobs:write'],
    { body: 'none', parameters: [ids.job] },
  ),
  doc(
    'post',
    '/v1/jobs/{jobId}/resume',
    'resumeJob',
    'Jobs',
    'Resume job',
    'Resumes a paused job and returns setup blockers if present.',
    ['jobs:write'],
    { body: 'none', parameters: [ids.job] },
  ),
  doc(
    'post',
    '/v1/jobs/{jobId}/trigger',
    'triggerJob',
    'Jobs',
    'Trigger job now',
    'Creates an immediate trigger subject to rate limits.',
    ['jobs:write'],
    { body: 'none', parameters: [ids.job], status: '202' },
  ),
  doc(
    'get',
    '/v1/triggers/{triggerId}/wait',
    'waitForTrigger',
    'Jobs',
    'Wait for trigger completion',
    'Long-polls for a previously accepted job trigger.',
    ['jobs:read'],
    { parameters: [ids.trigger] },
  ),
  doc(
    'get',
    '/v1/runs',
    'listRuns',
    'Runs',
    'List job runs',
    'Lists job runs visible to the API key app scope.',
    ['jobs:read'],
    { parameters: [query('jobId', 'Optional job id filter.')] },
  ),
  doc(
    'get',
    '/v1/runs/{runId}',
    'getRun',
    'Runs',
    'Get run',
    'Reads one job run after verifying app ownership.',
    ['jobs:read'],
    { parameters: [ids.run] },
  ),
  doc(
    'get',
    '/v1/runs/{runId}/events',
    'listRunEvents',
    'Runs',
    'List run events',
    'Lists runtime events projected into run-event shape.',
    ['jobs:read'],
    { parameters: [ids.run] },
  ),
  doc(
    'get',
    '/v1/webhooks',
    'listWebhooks',
    'Webhooks',
    'List outbound webhooks',
    'Lists outbound callback registrations.',
    ['webhooks:read'],
  ),
  doc(
    'post',
    '/v1/webhooks',
    'createWebhook',
    'Webhooks',
    'Create outbound webhook',
    'Registers an outbound callback URL for runtime events.',
    ['webhooks:write'],
    { body: 'json', status: '201' },
  ),
  doc(
    'patch',
    '/v1/webhooks/{webhookId}',
    'updateWebhook',
    'Webhooks',
    'Update outbound webhook',
    'Updates name, URL, secret, or enabled state.',
    ['webhooks:write'],
    { body: 'json', parameters: [ids.webhook] },
  ),
  doc(
    'delete',
    '/v1/webhooks/{webhookId}',
    'deleteWebhook',
    'Webhooks',
    'Delete outbound webhook',
    'Deletes an outbound webhook registration.',
    ['webhooks:write'],
    { body: 'none', parameters: [ids.webhook] },
  ),
  doc(
    'post',
    '/v1/webhooks/{webhookId}/test',
    'testWebhook',
    'Webhooks',
    'Send webhook test event',
    'Publishes a webhook test runtime event for delivery.',
    ['webhooks:write'],
    { body: 'none', parameters: [ids.webhook], status: '202' },
  ),
  doc(
    'post',
    '/v1/webhooks/{webhookId}/replay-dead-letter',
    'replayWebhookDeadLetters',
    'Webhooks',
    'Replay webhook dead letters',
    'Requeues dead-lettered webhook deliveries.',
    ['webhooks:write'],
    { body: 'none', parameters: [ids.webhook] },
  ),
  doc(
    'post',
    '/v1/webhooks/{webhookId}/purge-dead-letter',
    'purgeWebhookDeadLetters',
    'Webhooks',
    'Purge webhook dead letters',
    'Deletes dead-lettered webhook deliveries.',
    ['webhooks:write'],
    { body: 'none', parameters: [ids.webhook] },
  ),
  doc(
    'get',
    '/v1/ingresses',
    'listExternalIngresses',
    'External Ingresses',
    'List external ingresses',
    'Lists signed inbound authorities for systems without API keys.',
    ['ingresses:read'],
  ),
  doc(
    'post',
    '/v1/ingresses',
    'createExternalIngress',
    'External Ingresses',
    'Create external ingress',
    'Creates a signed ingress record with explicit target metadata.',
    ['ingresses:write'],
    { body: 'json', status: '201' },
  ),
  doc(
    'get',
    '/v1/ingresses/{ingressId}',
    'getExternalIngress',
    'External Ingresses',
    'Get external ingress',
    'Reads one signed ingress record.',
    ['ingresses:read'],
    { parameters: [ids.ingress] },
  ),
  doc(
    'patch',
    '/v1/ingresses/{ingressId}',
    'updateExternalIngress',
    'External Ingresses',
    'Update external ingress',
    'Updates ingress name, enabled state, or metadata.',
    ['ingresses:write'],
    { body: 'json', parameters: [ids.ingress] },
  ),
  doc(
    'delete',
    '/v1/ingresses/{ingressId}',
    'deleteExternalIngress',
    'External Ingresses',
    'Delete external ingress',
    'Deletes a signed ingress record.',
    ['ingresses:write'],
    { body: 'none', parameters: [ids.ingress] },
  ),
  doc(
    'post',
    '/v1/ingresses/{ingressId}/rotate',
    'rotateExternalIngressSecret',
    'External Ingresses',
    'Rotate external ingress secret',
    'Rotates the signing secret for an external ingress.',
    ['ingresses:write'],
    { body: 'none', parameters: [ids.ingress] },
  ),
  doc(
    'post',
    '/v1/ingresses/{ingressId}/invoke',
    'invokeExternalIngress',
    'External Ingresses',
    'Invoke external ingress',
    'Accepts a signed payload using Gantry ingress signature headers.',
    undefined,
    { body: 'json', parameters: [ids.ingress], status: '202' },
  ),
  doc(
    'post',
    '/v1/ingresses/{ingressId}/wait',
    'waitForExternalIngress',
    'External Ingresses',
    'Invoke and wait for external ingress',
    'Accepts a signed ingress payload and waits for the result.',
    undefined,
    { body: 'json', parameters: [ids.ingress] },
  ),
  doc(
    'get',
    '/v1/memory',
    'listMemory',
    'Memory',
    'List memory items',
    'Lists app-scoped memory items with optional subject filters.',
    ['memory:read'],
  ),
  doc(
    'post',
    '/v1/memory',
    'createMemory',
    'Memory',
    'Create memory item',
    'Directly saves an app memory item using canonical kinds.',
    ['memory:admin'],
    { body: 'json', status: '201' },
  ),
  doc(
    'post',
    '/v1/memory/search',
    'searchMemory',
    'Memory',
    'Search memory',
    'Searches app memory with configured subject filters.',
    ['memory:read'],
    { body: 'json' },
  ),
  doc(
    'patch',
    '/v1/memory/{memoryId}',
    'patchMemory',
    'Memory',
    'Patch memory item',
    'Updates mutable memory item fields.',
    ['memory:admin'],
    { body: 'json', parameters: [ids.memory] },
  ),
  doc(
    'delete',
    '/v1/memory/{memoryId}',
    'deleteMemory',
    'Memory',
    'Delete memory item',
    'Deletes a memory item in the requested subject scope.',
    ['memory:admin'],
    { body: 'none', parameters: [ids.memory] },
  ),
  doc(
    'post',
    '/v1/memory/dreaming/trigger',
    'triggerMemoryDreaming',
    'Memory',
    'Trigger memory dreaming',
    'Starts an app or agent scoped memory dreaming run.',
    ['memory:admin'],
    { body: 'json', status: '202' },
  ),
  doc(
    'get',
    '/v1/memory/dreaming/status',
    'getMemoryDreamingStatus',
    'Memory',
    'Get memory dreaming status',
    'Returns recent memory dreaming runs.',
    ['memory:read'],
  ),
  doc(
    'get',
    '/v1/skills/drafts',
    'listSkillDrafts',
    'Skills',
    'List skill drafts',
    'Lists local skill draft records.',
    ['skills:read'],
  ),
  doc(
    'post',
    '/v1/skills/drafts/upload',
    'uploadSkillDraft',
    'Skills',
    'Upload skill draft',
    'Imports a zip package as a local skill draft.',
    ['skills:admin'],
    { body: 'zip', status: '201' },
  ),
  doc(
    'post',
    '/v1/skills/drafts/{skillId}/approve',
    'approveSkillDraft',
    'Skills',
    'Approve skill draft',
    'Approves a reviewed skill draft and makes it selectable.',
    ['skills:admin'],
    { body: 'json', parameters: [ids.skill] },
  ),
  doc(
    'post',
    '/v1/skills/drafts/{skillId}/reject',
    'rejectSkillDraft',
    'Skills',
    'Reject skill draft',
    'Rejects a reviewed skill draft.',
    ['skills:admin'],
    { body: 'json', parameters: [ids.skill] },
  ),
  doc(
    'get',
    '/v1/skills/{skillId}/files',
    'listSkillFiles',
    'Skills',
    'List skill files',
    'Lists readable files for a skill artifact.',
    ['skills:read'],
    { parameters: [ids.skill] },
  ),
  doc(
    'get',
    '/v1/skills/{skillId}/files/{filePath}',
    'getSkillFile',
    'Skills',
    'Get skill file',
    'Reads one file from a skill artifact.',
    ['skills:read'],
    { parameters: [ids.skill, ids.file] },
  ),
  doc(
    'get',
    '/v1/agents/{agentId}/skills',
    'listAgentSkillBindings',
    'Skills',
    'List agent skill bindings',
    'Lists skills currently bound to an agent.',
    ['skills:read'],
    { parameters: [ids.agent] },
  ),
  doc(
    'put',
    '/v1/agents/{agentId}/skills/{skillId}',
    'bindSkillToAgent',
    'Skills',
    'Bind skill to agent',
    'Binds an approved skill and syncs settings desired state.',
    ['skills:admin'],
    { body: 'json', parameters: [ids.agent, ids.skill] },
  ),
  doc(
    'delete',
    '/v1/agents/{agentId}/skills/{skillId}',
    'unbindSkillFromAgent',
    'Skills',
    'Unbind skill from agent',
    'Removes a skill binding and syncs settings desired state.',
    ['skills:admin'],
    { body: 'none', parameters: [ids.agent, ids.skill] },
  ),
  doc(
    'get',
    '/v1/mcp-servers/drafts',
    'listMcpServerDrafts',
    'MCP Servers',
    'List MCP server drafts',
    'Lists draft MCP server definitions pending review.',
    ['mcp:read'],
  ),
  doc(
    'post',
    '/v1/mcp-servers/drafts',
    'createMcpServerDraft',
    'MCP Servers',
    'Create MCP server draft',
    'Creates a reviewable MCP server draft.',
    ['mcp:admin'],
    { body: 'json', status: '201' },
  ),
  doc(
    'get',
    '/v1/mcp-servers',
    'listMcpServers',
    'MCP Servers',
    'List MCP servers',
    'Lists MCP server definitions, optionally filtered by status.',
    ['mcp:read'],
  ),
  doc(
    'post',
    '/v1/mcp-servers/drafts/{serverId}/approve',
    'approveMcpServerDraft',
    'MCP Servers',
    'Approve MCP server draft',
    'Approves a reviewed MCP server draft.',
    ['mcp:admin'],
    { body: 'json', parameters: [ids.server] },
  ),
  doc(
    'post',
    '/v1/mcp-servers/drafts/{serverId}/reject',
    'rejectMcpServerDraft',
    'MCP Servers',
    'Reject MCP server draft',
    'Rejects a reviewed MCP server draft.',
    ['mcp:admin'],
    { body: 'json', parameters: [ids.server] },
  ),
  doc(
    'post',
    '/v1/mcp-servers/{serverId}/disable',
    'disableMcpServer',
    'MCP Servers',
    'Disable MCP server',
    'Disables an approved MCP server and syncs settings.',
    ['mcp:admin'],
    { body: 'json', parameters: [ids.server] },
  ),
  doc(
    'post',
    '/v1/mcp-servers/{serverId}/test',
    'testMcpServer',
    'MCP Servers',
    'Test MCP server',
    'Runs server-side MCP definition validation.',
    ['mcp:admin'],
    { body: 'json', parameters: [ids.server] },
  ),
  doc(
    'get',
    '/v1/agents/{agentId}/mcp-servers',
    'listAgentMcpServerBindings',
    'MCP Servers',
    'List agent MCP server bindings',
    'Lists MCP servers currently bound to an agent.',
    ['mcp:read'],
    { parameters: [ids.agent] },
  ),
  doc(
    'put',
    '/v1/agents/{agentId}/mcp-servers/{serverId}',
    'bindMcpServerToAgent',
    'MCP Servers',
    'Bind MCP server to agent',
    'Binds an approved MCP server and syncs settings.',
    ['mcp:admin', 'agents:admin'],
    { body: 'json', parameters: [ids.agent, ids.server] },
  ),
  doc(
    'patch',
    '/v1/agents/{agentId}/mcp-servers/{serverId}',
    'updateAgentMcpServerBinding',
    'MCP Servers',
    'Update agent MCP server binding',
    'Updates binding version or policy metadata.',
    ['mcp:admin', 'agents:admin'],
    { body: 'json', parameters: [ids.agent, ids.server] },
  ),
  doc(
    'delete',
    '/v1/agents/{agentId}/mcp-servers/{serverId}',
    'unbindMcpServerFromAgent',
    'MCP Servers',
    'Unbind MCP server from agent',
    'Removes an MCP server binding and syncs settings.',
    ['mcp:admin', 'agents:admin'],
    { body: 'none', parameters: [ids.agent, ids.server] },
  ),
];
