import type { JsonSchema } from './openapi-route-helpers.js';
import { AGENT_HARNESSES } from '../../shared/agent-engine.js';
import {
  peopleOpenApiRequestSchemas,
  peopleOpenApiResponseSchemas,
} from './openapi-people.js';

const ref = (name: string): JsonSchema => ({
  $ref: `#/components/schemas/${name}`,
});

const onboardingVerification: JsonSchema = {
  type: 'object',
  additionalProperties: false,
  required: ['id', 'status'],
  properties: {
    id: { type: 'string', format: 'uuid' },
    challenge: { type: 'string' },
    challengeText: { type: 'string' },
    status: {
      type: 'string',
      enum: [
        'pending',
        'inbound_received',
        'satisfied',
        'projection_failed',
        'expired',
        'completed',
      ],
    },
    expiresAt: { type: 'string', format: 'date-time' },
    satisfiedAt: { type: ['string', 'null'], format: 'date-time' },
    completedAt: { type: ['string', 'null'], format: 'date-time' },
    failureCode: {
      type: ['string', 'null'],
      enum: [
        'VERIFICATION_PENDING',
        'VERIFICATION_EXPIRED',
        'RUNTIME_PROJECTION_FAILED',
        null,
      ],
    },
  },
};

export const openApiResponseSchemas: Record<string, JsonSchema> = {
  getBrowserOnboardingStatus: {
    type: 'object',
    additionalProperties: false,
    required: ['firstRun', 'resume'],
    properties: {
      firstRun: { type: 'boolean' },
      resume: {
        type: ['object', 'null'],
        additionalProperties: false,
        required: [
          'id',
          'setupId',
          'name',
          'accountId',
          'channelId',
          'conversationId',
          'approver',
          'assignmentReady',
          'verificationId',
          'challenge',
          'challengeText',
          'hasWorkspace',
          'step',
        ],
        properties: {
          id: { type: 'string' },
          setupId: { type: 'string', format: 'uuid' },
          name: { type: 'string' },
          accountId: { type: ['string', 'null'] },
          channelId: { type: ['string', 'null'] },
          conversationId: { type: ['string', 'null'] },
          approver: { type: ['string', 'null'] },
          assignmentReady: { type: 'boolean' },
          verificationId: { type: ['string', 'null'], format: 'uuid' },
          challenge: { type: ['string', 'null'] },
          challengeText: { type: ['string', 'null'] },
          hasWorkspace: { type: 'boolean' },
          step: { type: 'integer', enum: [2, 3, 4] },
        },
      },
    },
  },
  getBrowserOnboardingChannelManifest: {
    type: 'object',
    required: ['manifestJson', 'createUrl', 'permissionGroups'],
    properties: {
      manifestJson: { type: 'string' },
      createUrl: { type: 'string', format: 'uri' },
      permissionGroups: {
        type: 'array',
        items: {
          type: 'object',
          additionalProperties: false,
          required: ['title', 'description', 'scopes'],
          properties: {
            title: { type: 'string' },
            description: { type: 'string' },
            scopes: { type: 'array', items: { type: 'string' } },
          },
        },
      },
    },
  },
  createBrowserOnboardingSetup: {
    type: 'object',
    required: ['setup', 'agent'],
    properties: {
      setup: {
        type: 'object',
        additionalProperties: false,
        required: ['id', 'desiredStateRevision', 'replayed'],
        properties: {
          id: { type: 'string', format: 'uuid' },
          desiredStateRevision: { type: 'integer', minimum: 1 },
          replayed: { type: 'boolean' },
        },
      },
      agent: {
        type: 'object',
        additionalProperties: false,
        required: ['id', 'name'],
        properties: { id: { type: 'string' }, name: { type: 'string' } },
      },
    },
  },
  createBrowserOnboardingVerification: {
    type: 'object',
    required: ['verification'],
    properties: { verification: onboardingVerification },
  },
  getBrowserOnboardingVerification: {
    type: 'object',
    required: ['verification'],
    properties: { verification: onboardingVerification },
  },
  projectBrowserOnboardingVerification: {
    type: 'object',
    required: ['verification'],
    properties: { verification: onboardingVerification },
  },
  bindMcpServerToAgent: ref('AgentMcpServerBindingResponse'),
  bindSkillToAgent: ref('AgentSkillBindingResponse'),
  connectMcpServer: ref('McpServerResponse'),
  createAgent: ref('Agent'),
  createExternalIngress: ref('ExternalIngress'),
  createJob: ref('JobCreateResponse'),
  createMemory: ref('MemoryItemResponse'),
  createProviderAccount: ref('ProviderAccount'),
  createWebhook: ref('Webhook'),
  deleteExternalIngress: ref('DeleteResponse'),
  deleteJob: ref('DeleteResponse'),
  deleteMemory: ref('DeleteResponse'),
  deleteWebhook: ref('DeleteResponse'),
  disableConversationInstall: ref('ConversationInstallDeleteResponse'),
  disableMcpServer: ref('McpServerResponse'),
  disableProviderAccount: ref('ProviderAccountDeleteResponse'),
  discoverProviderConversations: ref('ConversationListResponse'),
  enableConversationInstall: ref('ConversationInstall'),
  ensureSession: ref('SessionEnsureResponse'),
  getAgent: ref('Agent'),
  getAgentAdminSummary: ref('AgentAdminSummaryResponse'),
  getAgentDelegates: ref('AgentDelegatesResponse'),
  getAgentAccess: ref('AgentAccessResponse'),
  listAgentProfileFiles: ref('AgentProfileFilesResponse'),
  getAgentProfileFile: ref('AgentProfileFileContentResponse'),
  setAgentProfileFile: ref('AgentProfileFileContentResponse'),
  getCapability: ref('CapabilityManifest'),
  getConversation: ref('Conversation'),
  getDoctor: ref('DoctorResponse'),
  getExternalIngress: ref('ExternalIngress'),
  getHealth: ref('HealthResponse'),
  getJob: ref('Job'),
  getMemoryDreamingStatus: ref('MemoryDreamingStatusResponse'),
  getObserverStatus: ref('ObserverStatusResponse'),
  getMcpServer: ref('McpServerResponse'),
  getModelDefaults: ref('ModelDefaultsResponse'),
  previewGuidedAction: ref('GuidedActionPreview'),
  executeGuidedAction: ref('GuidedActionResult'),
  getProviderAccount: ref('ProviderAccount'),
  getRun: ref('Run'),
  getSession: ref('SessionDetails'),
  getSettings: ref('SettingsResponse'),
  getStatus: ref('ControlStatusResponse'),
  getSkillFile: ref('SkillFileResponse'),
  invokeExternalIngress: ref('ExternalIngressInvokeResponse'),
  invokeLlmChatCompletions: ref('LlmChatCompletionsResponse'),
  invokeLlmMessages: ref('LlmMessagesResponse'),
  invokeLlmMessagesCountTokens: ref('LlmMessagesCountTokensResponse'),
  listConversationInstalls: ref('ConversationInstallListResponse'),
  listAgentMcpServerBindings: ref('AgentMcpServerBindingListResponse'),
  listAgentSkillBindings: ref('AgentSkillBindingListResponse'),
  listAgents: ref('AgentListResponse'),
  getInventory: ref('InventoryResponse'),
  listCapabilities: ref('CapabilityListResponse'),
  listConversationApprovers: ref('ConversationApproversResponse'),
  listConversationMessages: ref('ConversationMessageListResponse'),
  listConversationThreads: ref('ConversationThreadListResponse'),
  listConversations: ref('ConversationListResponse'),
  listExternalIngresses: ref('ExternalIngressListResponse'),
  listJobEvents: ref('JobEventListResponse'),
  listJobs: ref('JobListResponse'),
  listMcpServers: ref('McpServerPageResponse'),
  listMemory: ref('MemoryListResponse'),
  listMemoryReviews: ref('MemoryReviewPageResponse'),
  getMemoryReview: ref('MemoryReviewDetailResponse'),
  decideMemoryReview: ref('MemoryReviewDetailResponse'),
  listObserverInsights: ref('ObserverInsightListResponse'),
  previewObserverDigest: ref('ObserverDigestPreviewResponse'),
  listObserverDeliveries: ref('ObserverDigestDeliveryListResponse'),
  listModelCredentials: ref('ModelCredentialListResponse'),
  listModels: ref('ModelListResponse'),
  listOrStreamSessionEvents: ref('SessionRuntimeEventListResponse'),
  listProviderAccounts: ref('ProviderAccountListResponse'),
  listProviders: ref('ProviderListResponse'),
  listRunEvents: ref('RuntimeEventListResponse'),
  listRuns: ref('RunListResponse'),
  listSessionInteractions: ref('SessionInteractionListResponse'),
  listSessionMessages: ref('SessionMessageListResponse'),
  listSessionRuns: ref('RunListResponse'),
  respondSessionInteraction: ref('SessionInteractionRespondResponse'),
  listSkillFiles: ref('SkillFilesResponse'),
  listSkills: ref('SkillListResponse'),
  listWebhooks: ref('WebhookListResponse'),
  patchMemory: ref('MemoryItemResponse'),
  patchModelCredential: ref('ModelCredentialMutationResponse'),
  patchModelDefaults: ref('ModelDefaultsResponse'),
  patchSettingsReadOnly: ref('ErrorEnvelope'),
  putModelCredential: ref('ModelCredentialMutationResponse'),
  disableModelCredential: ref('ModelCredentialMutationResponse'),
  previewModelSelection: ref('ModelPreviewResponse'),
  pauseJob: ref('JobPauseResponse'),
  purgeWebhookDeadLetters: ref('CountResponse'),
  replayWebhookDeadLetters: ref('CountResponse'),
  replaceAgentAccess: ref('AgentAccessResponse'),
  replaceAgentDelegates: ref('SettingsRevisionResponse'),
  replaceConversationApprovers: ref('ConversationApproversResponse'),
  resumeJob: ref('JobResumeResponse'),
  rotateExternalIngressSecret: ref('ExternalIngress'),
  searchMemory: ref('MemorySearchResponse'),
  sendSessionMessage: ref('SendSessionMessageResponse'),
  testMcpServer: ref('McpServerTestResponse'),
  testWebhook: ref('WebhookTestResponse'),
  triggerJob: ref('JobTriggerResponse'),
  triggerMemoryDreaming: ref('MemoryDreamingResponse'),
  queryUsage: ref('UsageQueryResponse'),
  unbindMcpServerFromAgent: ref('AgentMcpServerBindingResponse'),
  unbindSkillFromAgent: ref('AgentSkillBindingResponse'),
  updateAgent: ref('Agent'),
  updateConversationInstall: ref('ConversationInstall'),
  updateAgentMcpServerBinding: ref('AgentMcpServerBindingResponse'),
  updateExternalIngress: ref('ExternalIngress'),
  updateJob: ref('Job'),
  updateProviderAccount: ref('ProviderAccount'),
  updateWebhook: ref('Webhook'),
  installSkill: ref('SkillResponse'),
  waitForExternalIngress: ref('ExternalIngressInvokeResponse'),
  waitForSessionEvent: ref('SessionWaitEventResponse'),
  waitForTrigger: ref('TriggerWaitResponse'),
  importBrainPages: ref('BrainImportResponse'),
  getBrainStatus: ref('BrainStatusResponse'),
  ...peopleOpenApiResponseSchemas,
};

export const openApiRequestSchemas: Record<string, JsonSchema> = {
  createBrowserOnboardingSetup: {
    type: 'object',
    additionalProperties: false,
    required: [
      'name',
      'title',
      'responsibilities',
      'modelAlias',
      'agentHarness',
    ],
    properties: {
      name: { type: 'string', minLength: 1 },
      title: { type: 'string', minLength: 1 },
      responsibilities: { type: 'array', items: { type: 'string' } },
      modelAlias: { type: 'string', minLength: 1 },
      agentHarness: {
        type: 'string',
        enum: [...AGENT_HARNESSES],
      },
    },
  },
  createBrowserOnboardingVerification: {
    type: 'object',
    additionalProperties: false,
    required: ['agentId', 'conversationId'],
    properties: {
      agentId: { type: 'string', minLength: 1 },
      conversationId: { type: 'string', minLength: 1 },
    },
  },
  bindMcpServerToAgent: ref('AgentMcpServerBindingRequest'),
  bindSkillToAgent: ref('AgentSkillBindingRequest'),
  connectMcpServer: ref('McpServerRequest'),
  createAgent: ref('AgentCreateRequest'),
  createExternalIngress: ref('ExternalIngressRequest'),
  createJob: ref('JobCreateRequest'),
  createMemory: ref('MemorySaveRequest'),
  decideMemoryReview: ref('MemoryReviewDecisionRequest'),
  createProviderAccount: ref('ProviderAccountRequest'),
  createWebhook: ref('WebhookCreateRequest'),
  disableMcpServer: ref('DisableMcpServerRequest'),
  discoverProviderConversations: ref('DiscoverProviderConversationsRequest'),
  enableConversationInstall: ref('ConversationInstallRequest'),
  ensureSession: ref('SessionEnsureRequest'),
  invokeExternalIngress: ref('ExternalIngressInvokeRequest'),
  invokeLlmChatCompletions: ref('LlmChatCompletionsRequest'),
  invokeLlmMessages: ref('LlmMessagesRequest'),
  ...peopleOpenApiRequestSchemas,
  invokeLlmMessagesCountTokens: ref('LlmMessagesCountTokensRequest'),
  importBrainPages: ref('BrainImportRequest'),
  patchMemory: ref('MemorySaveRequest'),
  patchModelCredential: ref('ModelCredentialPatchRequest'),
  patchModelDefaults: ref('ModelDefaultsPatchRequest'),
  putModelCredential: ref('ModelCredentialWriteRequest'),
  previewModelSelection: ref('ModelPreviewRequest'),
  previewGuidedAction: ref('GuidedActionRequest'),
  executeGuidedAction: ref('GuidedActionRequest'),
  patchSettingsReadOnly: ref('ReadOnlySettingsPatchRequest'),
  replaceAgentAccess: ref('AgentAccessRequest'),
  replaceAgentDelegates: ref('ReplaceAgentDelegatesRequest'),
  setAgentProfileFile: ref('PutAgentProfileFileRequest'),
  replaceConversationApprovers: ref('ConversationApproversRequest'),
  respondSessionInteraction: ref('SessionInteractionRespondRequest'),
  searchMemory: ref('MemorySearchRequest'),
  sendSessionMessage: ref('SendSessionMessageRequest'),
  testMcpServer: ref('McpServerTestRequest'),
  triggerMemoryDreaming: ref('MemoryDreamingTriggerRequest'),
  updateAgent: ref('AgentUpdateRequest'),
  updateConversationInstall: ref('ConversationInstallRequest'),
  updateAgentMcpServerBinding: ref('AgentMcpServerBindingRequest'),
  updateExternalIngress: ref('ExternalIngressRequest'),
  updateJob: ref('JobUpdateRequest'),
  updateProviderAccount: ref('ProviderAccountUpdateRequest'),
  updateWebhook: ref('WebhookUpdateRequest'),
  waitForExternalIngress: ref('ExternalIngressInvokeRequest'),
};
