import { doc, ids, query, type RouteDoc } from './openapi-route-helpers.js';

export const coreOpenApiRouteDocs: RouteDoc[] = [
  doc(
    'get',
    '/v1/health',
    'getHealth',
    'System',
    'Check control server health',
    'Returns runtime transport details and enabled feature flags.',
    ['sessions:read'],
  ),
  doc(
    'get',
    '/v1/doctor',
    'getDoctor',
    'System',
    'Run lightweight control diagnostics',
    'Reports control-plane readiness checks.',
    ['sessions:read'],
  ),
  doc(
    'get',
    '/v1/models',
    'listModels',
    'Models',
    'List registered model aliases',
    'Returns provider-neutral model catalog entries.',
    ['sessions:read'],
  ),
  doc(
    'get',
    '/v1/models/defaults',
    'getModelDefaults',
    'Models',
    'Read configured and effective model defaults',
    'Returns provider-neutral defaults for chat, jobs, and memory tasks.',
    ['sessions:read'],
  ),
  doc(
    'patch',
    '/v1/models/defaults',
    'patchModelDefaults',
    'Models',
    'Update model defaults',
    'Applies provider, chat, jobs, and memory reset changes to settings.yaml.',
    ['agents:admin'],
    { body: 'json' },
  ),
  doc(
    'post',
    '/v1/models/preview',
    'previewModelSelection',
    'Models',
    'Preview model selection',
    'Explains what model chat, jobs, or memory will use and why. Chat, jobs, and memory previews require sessions:read; stored job previews require jobs:read.',
    ['sessions:read', 'jobs:read'],
    { body: 'json' },
  ),
  doc(
    'get',
    '/v1/settings',
    'getSettings',
    'Settings',
    'Read public runtime settings',
    'Returns the non-secret settings projection.',
    ['agents:admin'],
  ),
  doc(
    'patch',
    '/v1/settings',
    'patchSettingsReadOnly',
    'Settings',
    'Attempt a settings mutation',
    'The typed settings API is read-only and returns SETTINGS_READ_ONLY.',
    ['agents:admin'],
    { body: 'json' },
  ),
  doc(
    'get',
    '/v1/agents',
    'listAgents',
    'Agents',
    'List agents',
    'Lists user-facing agents in the API key app scope.',
    ['agents:admin'],
  ),
  doc(
    'post',
    '/v1/agents',
    'createAgent',
    'Agents',
    'Create an agent',
    'Creates an agent and syncs settings desired state.',
    ['agents:admin'],
    { body: 'json', status: '201' },
  ),
  doc(
    'get',
    '/v1/agents/{agentId}',
    'getAgent',
    'Agents',
    'Get an agent',
    'Reads one agent by id.',
    ['agents:admin'],
    { parameters: [ids.agent] },
  ),
  doc(
    'patch',
    '/v1/agents/{agentId}',
    'updateAgent',
    'Agents',
    'Update an agent',
    'Updates agent name or lifecycle status.',
    ['agents:admin'],
    { body: 'json', parameters: [ids.agent] },
  ),
  doc(
    'get',
    '/v1/agents/{agentId}/admin',
    'getAgentAdminSummary',
    'Agents',
    'Get agent admin summary',
    'Returns agent metadata, capabilities, and bound conversations.',
    ['agents:admin'],
    { parameters: [ids.agent] },
  ),
  doc(
    'get',
    '/v1/inventory',
    'getInventory',
    'Capabilities',
    'List global inventory',
    'Returns read-only global onboarded tools, skills, and MCP servers.',
    ['agents:admin'],
  ),
  doc(
    'get',
    '/v1/capabilities',
    'listCapabilities',
    'Capabilities',
    'List approved capabilities',
    'Returns approved immutable capability manifests.',
    ['agents:admin'],
  ),
  doc(
    'get',
    '/v1/capabilities/{capabilityId}',
    'getCapability',
    'Capabilities',
    'Get one approved capability',
    'Returns the immutable capability manifest and projection metadata.',
    ['agents:admin'],
    { parameters: [ids.capability] },
  ),
  doc(
    'get',
    '/v1/agents/{agentId}/sources',
    'getAgentSources',
    'Capabilities',
    'Get attached agent sources',
    'Returns attached skills, MCP servers, and tool sources without granting authority.',
    ['agents:admin'],
    { parameters: [ids.agent] },
  ),
  doc(
    'put',
    '/v1/agents/{agentId}/sources',
    'replaceAgentSources',
    'Capabilities',
    'Replace attached agent sources',
    'Replaces source attachments and exports readable settings entries.',
    ['agents:admin'],
    { body: 'json', parameters: [ids.agent] },
  ),
  doc(
    'get',
    '/v1/agents/{agentId}/capabilities',
    'getAgentCapabilities',
    'Capabilities',
    'Get selected agent capabilities',
    'Returns selected ids plus the canonical tool access view.',
    ['agents:admin'],
    { parameters: [ids.agent] },
  ),
  doc(
    'put',
    '/v1/agents/{agentId}/capabilities',
    'replaceAgentCapabilities',
    'Capabilities',
    'Replace selected agent capabilities',
    'Replaces capability selection and exports readable settings entries.',
    ['agents:admin'],
    { body: 'json', parameters: [ids.agent] },
  ),
  doc(
    'post',
    '/v1/sessions/ensure',
    'ensureSession',
    'Sessions',
    'Ensure an SDK session',
    'Creates or reuses an app-scoped durable session.',
    ['sessions:write'],
    { body: 'json' },
  ),
  doc(
    'get',
    '/v1/sessions/{sessionId}',
    'getSession',
    'Sessions',
    'Get session details',
    'Returns app-scoped session metadata.',
    ['sessions:read'],
    { parameters: [ids.session] },
  ),
  doc(
    'get',
    '/v1/sessions/{sessionId}/messages',
    'listSessionMessages',
    'Sessions',
    'List session messages',
    'Lists durable session message history.',
    ['sessions:read'],
    {
      parameters: [ids.session, query('limit', 'Maximum number of messages.')],
    },
  ),
  doc(
    'post',
    '/v1/sessions/{sessionId}/messages',
    'sendSessionMessage',
    'Sessions',
    'Accept a session message',
    'Persists an inbound SDK message and enqueues processing.',
    ['sessions:write'],
    { body: 'json', parameters: [ids.session], status: '202' },
  ),
  doc(
    'get',
    '/v1/sessions/{sessionId}/events',
    'listOrStreamSessionEvents',
    'Sessions',
    'List or stream session events',
    'Returns JSON history or Server-Sent Events.',
    ['sessions:read'],
    { parameters: [ids.session, query('afterEventId', 'Event cursor.')] },
  ),
  doc(
    'get',
    '/v1/sessions/{sessionId}/wait',
    'waitForSessionEvent',
    'Sessions',
    'Wait for the next visible session event',
    'Long-polls for the next visible runtime event.',
    ['sessions:read'],
    {
      parameters: [
        ids.session,
        query('afterEventId', 'Event cursor.'),
        query('timeoutMs', 'Timeout in milliseconds.'),
      ],
    },
  ),
  doc(
    'get',
    '/v1/sessions/{sessionId}/runs',
    'listSessionRuns',
    'Sessions',
    'List session runs',
    'Lists runtime runs associated with a session.',
    ['sessions:read'],
    { parameters: [ids.session] },
  ),
  doc(
    'get',
    '/v1/providers',
    'listProviders',
    'Providers',
    'List channel providers',
    'Lists provider adapters that can be connected.',
    ['providers:read'],
  ),
  doc(
    'get',
    '/v1/provider-connections',
    'listProviderConnections',
    'Providers',
    'List provider connections',
    'Lists installed provider connections.',
    ['providers:read'],
  ),
  doc(
    'post',
    '/v1/provider-connections',
    'createProviderConnection',
    'Providers',
    'Create a provider connection',
    'Creates a connection using runtime secret references.',
    ['providers:admin'],
    { body: 'json', status: '201' },
  ),
  doc(
    'get',
    '/v1/provider-connections/{providerConnectionId}',
    'getProviderConnection',
    'Providers',
    'Get provider connection',
    'Reads a provider connection.',
    ['providers:read'],
    { parameters: [ids.providerConnection] },
  ),
  doc(
    'patch',
    '/v1/provider-connections/{providerConnectionId}',
    'updateProviderConnection',
    'Providers',
    'Update provider connection',
    'Updates connection metadata, status, config, and secret refs.',
    ['providers:admin'],
    { body: 'json', parameters: [ids.providerConnection] },
  ),
  doc(
    'delete',
    '/v1/provider-connections/{providerConnectionId}',
    'disableProviderConnection',
    'Providers',
    'Disable provider connection',
    'Disables a provider connection and syncs settings.',
    ['providers:admin'],
    { body: 'none', parameters: [ids.providerConnection] },
  ),
  doc(
    'post',
    '/v1/provider-connections/{providerConnectionId}/discover-conversations',
    'discoverProviderConversations',
    'Providers',
    'Discover provider conversations',
    'Discovers provider-side conversations available for binding.',
    ['providers:admin'],
    { body: 'json', parameters: [ids.providerConnection] },
  ),
  doc(
    'get',
    '/v1/conversations',
    'listConversations',
    'Conversations',
    'List conversations',
    'Lists normalized conversations.',
    ['conversations:read'],
    {
      parameters: [
        query('providerConnectionId', 'Filter by provider connection id.'),
      ],
    },
  ),
  doc(
    'get',
    '/v1/conversations/{conversationId}',
    'getConversation',
    'Conversations',
    'Get conversation',
    'Reads one normalized conversation.',
    ['conversations:read'],
    { parameters: [ids.conversation] },
  ),
  doc(
    'get',
    '/v1/conversations/{conversationId}/approvers',
    'listConversationApprovers',
    'Conversations',
    'List conversation approvers',
    'Returns the control approver allowlist.',
    ['conversations:read'],
    { parameters: [ids.conversation] },
  ),
  doc(
    'put',
    '/v1/conversations/{conversationId}/approvers',
    'replaceConversationApprovers',
    'Conversations',
    'Replace conversation approvers',
    'Replaces the allowlist after membership validation.',
    ['conversations:admin'],
    { body: 'json', parameters: [ids.conversation] },
  ),
  doc(
    'get',
    '/v1/conversations/{conversationId}/threads',
    'listConversationThreads',
    'Conversations',
    'List conversation threads',
    'Lists normalized threads or topics.',
    ['conversations:read'],
    { parameters: [ids.conversation] },
  ),
  doc(
    'get',
    '/v1/conversations/{conversationId}/messages',
    'listConversationMessages',
    'Conversations',
    'List conversation messages',
    'Lists durable messages, optionally scoped to a thread.',
    ['messages:read'],
    {
      parameters: [
        ids.conversation,
        query('threadId', 'Thread or topic id.'),
        query('after', 'Cursor or timestamp.'),
        query('limit', 'Maximum number of messages.'),
      ],
    },
  ),
  doc(
    'get',
    '/v1/agents/{agentId}/conversation-bindings',
    'listAgentConversationBindings',
    'Conversations',
    'List agent conversation bindings',
    'Lists conversations currently bound to an agent.',
    ['conversations:read'],
    { parameters: [ids.agent] },
  ),
  doc(
    'put',
    '/v1/agents/{agentId}/conversation-bindings/{conversationId}',
    'enableAgentConversationBinding',
    'Conversations',
    'Enable an agent conversation binding',
    'Binds an agent to a conversation and projects the runtime route.',
    ['agents:admin', 'conversations:admin'],
    { body: 'json', parameters: [ids.agent, ids.conversation] },
  ),
  doc(
    'patch',
    '/v1/agents/{agentId}/conversation-bindings/{conversationId}',
    'updateAgentConversationBinding',
    'Conversations',
    'Update an agent conversation binding',
    'Updates binding trigger, sender, or thread policy.',
    ['agents:admin', 'conversations:admin'],
    { body: 'json', parameters: [ids.agent, ids.conversation] },
  ),
  doc(
    'delete',
    '/v1/agents/{agentId}/conversation-bindings/{conversationId}',
    'disableAgentConversationBinding',
    'Conversations',
    'Disable an agent conversation binding',
    'Disables a binding and removes the live runtime route.',
    ['agents:admin', 'conversations:admin'],
    {
      body: 'none',
      parameters: [
        ids.agent,
        ids.conversation,
        query('threadId', 'Optional thread binding to disable.'),
      ],
    },
  ),
];
