import type { JsonSchema } from './openapi-route-helpers.js';

const isoDateTime = { type: 'string', format: 'date-time' };
const metadata = { type: 'object', additionalProperties: true };
const stringArray = { type: 'array', items: { type: 'string' } };
const envelope = (name: string, schema: JsonSchema): JsonSchema => ({
  type: 'object',
  required: [name],
  properties: { [name]: schema },
});
const arrayEnvelope = (name: string, itemRef: string): JsonSchema =>
  envelope(name, {
    type: 'array',
    items: { $ref: `#/components/schemas/${itemRef}` },
  });

export const extensionOpenApiSchemas: Record<string, JsonSchema> = {
  MemoryItem: {
    type: 'object',
    required: ['id', 'appId', 'kind', 'content', 'createdAt'],
    properties: {
      id: { type: 'string' },
      appId: { type: 'string' },
      agentId: { type: 'string' },
      userId: { type: 'string' },
      groupId: { type: 'string' },
      channelId: { type: 'string' },
      threadId: { type: 'string' },
      kind: {
        type: 'string',
        enum: ['preference', 'decision', 'fact', 'correction', 'constraint'],
      },
      content: { type: 'string' },
      metadata,
      createdAt: isoDateTime,
      updatedAt: isoDateTime,
    },
  },
  MemoryListResponse: arrayEnvelope('memories', 'MemoryItem'),
  MemorySearchResponse: arrayEnvelope('results', 'MemoryItem'),
  MemoryItemResponse: envelope('memory', {
    $ref: '#/components/schemas/MemoryItem',
  }),
  MemorySaveRequest: {
    type: 'object',
    required: ['kind', 'content'],
    properties: {
      appId: { type: 'string' },
      agentId: { type: 'string' },
      userId: { type: 'string' },
      groupId: { type: 'string' },
      channelId: { type: 'string' },
      threadId: { type: 'string' },
      kind: {
        type: 'string',
        enum: ['preference', 'decision', 'fact', 'correction', 'constraint'],
      },
      content: { type: 'string' },
      metadata,
    },
  },
  MemorySearchRequest: {
    type: 'object',
    required: ['query'],
    properties: {
      appId: { type: 'string' },
      query: { type: 'string' },
      limit: { type: 'integer', minimum: 1 },
      agentId: { type: 'string' },
      userId: { type: 'string' },
      groupId: { type: 'string' },
    },
  },
  MemoryDreamingTriggerRequest: {
    type: 'object',
    additionalProperties: false,
    properties: {
      appId: { type: 'string' },
      agentId: { type: 'string' },
      userId: { type: 'string' },
      groupId: { type: 'string' },
      channelId: { type: 'string' },
      threadId: { type: 'string' },
      subjectType: {
        type: 'string',
        enum: ['user', 'group', 'channel', 'common'],
      },
      subjectId: { type: 'string' },
      phase: { type: 'string', enum: ['light', 'rem', 'deep', 'all'] },
      dryRun: { type: 'boolean' },
      timeoutMs: { type: 'number', minimum: 0 },
      deadlineAtMs: { type: 'number', minimum: 0 },
    },
  },
  MemoryDreamingResponse: envelope('run', metadata),
  MemoryDreamingStatusResponse: envelope('runs', {
    type: 'array',
    items: metadata,
  }),
  ObserverOwner: {
    type: ['object', 'null'],
    required: [
      'recipient',
      'conversation',
      'conversationJid',
      'providerAccountId',
    ],
    properties: {
      recipient: { type: 'string' },
      conversation: { type: 'string' },
      conversationJid: { type: 'string' },
      providerAccountId: { type: 'string' },
    },
  },
  ObserverStatusResponse: {
    type: 'object',
    required: [
      'enabled',
      'activation',
      'message',
      'dreamingEnabled',
      'owner',
      'counts',
    ],
    properties: {
      enabled: { type: 'boolean' },
      activation: {
        type: 'string',
        enum: [
          'disabled',
          'configuration_required',
          'evidence_accumulating',
          'active',
        ],
      },
      message: { type: 'string' },
      dreamingEnabled: { type: 'boolean' },
      owner: { $ref: '#/components/schemas/ObserverOwner' },
      counts: {
        type: 'object',
        required: ['evidence', 'insights', 'pendingInsights'],
        properties: {
          evidence: { type: 'integer', minimum: 0 },
          insights: { type: 'integer', minimum: 0 },
          pendingInsights: { type: 'integer', minimum: 0 },
        },
      },
    },
  },
  ProactiveInsight: {
    type: 'object',
    required: [
      'id',
      'appId',
      'subject',
      'insightType',
      'title',
      'summary',
      'evidenceRefs',
      'batchSnapshotAt',
      'evidenceVersion',
      'canonicalSignature',
      'signatureEmbeddingRef',
      'confidence',
      'priorityScore',
      'state',
      'cooldownUntil',
      'resolvedAt',
      'surfacedAt',
      'recipient',
      'deliveryId',
      'createdAt',
      'updatedAt',
    ],
    properties: {
      id: { type: 'string' },
      appId: { type: 'string' },
      subject: { type: 'string' },
      insightType: {
        type: 'string',
        enum: [
          'commitment',
          'contradiction',
          'open_question',
          'stale_fact',
          'decision_without_owner',
          'duplicated_work',
          'repetition',
        ],
      },
      title: { type: 'string' },
      summary: { type: 'string' },
      evidenceRefs: {
        type: 'array',
        items: {
          type: 'object',
          required: ['conversationId', 'messageId', 'ts'],
          properties: {
            conversationId: { type: 'string' },
            messageId: { type: 'string' },
            ts: { type: 'string' },
          },
        },
      },
      batchSnapshotAt: isoDateTime,
      evidenceVersion: { type: 'integer', minimum: 1 },
      canonicalSignature: { type: 'string' },
      signatureEmbeddingRef: { type: ['string', 'null'] },
      confidence: { type: 'number', minimum: 0, maximum: 1 },
      priorityScore: { type: 'number' },
      state: {
        type: 'string',
        enum: ['pending', 'claimed', 'sent', 'cooldown', 'resolved', 'dropped'],
      },
      cooldownUntil: { type: ['string', 'null'], format: 'date-time' },
      resolvedAt: { type: ['string', 'null'], format: 'date-time' },
      surfacedAt: { type: ['string', 'null'], format: 'date-time' },
      recipient: { type: 'string' },
      deliveryId: { type: ['string', 'null'] },
      createdAt: isoDateTime,
      updatedAt: isoDateTime,
    },
  },
  ObserverInsightListResponse: {
    type: 'object',
    required: ['insights', 'nextCursor'],
    properties: {
      insights: {
        type: 'array',
        items: { $ref: '#/components/schemas/ProactiveInsight' },
      },
      nextCursor: { type: ['string', 'null'] },
    },
  },
  Skill: {
    type: 'object',
    required: ['id', 'appId', 'name', 'status'],
    properties: {
      id: { type: 'string' },
      appId: { type: 'string' },
      name: { type: 'string' },
      displayName: { type: 'string' },
      description: { type: 'string' },
      status: { type: 'string' },
      requiredEnvVars: { type: 'array', items: { type: 'string' } },
      actionPermissions: {
        type: 'array',
        items: {
          type: 'object',
          required: [
            'id',
            'capabilityId',
            'displayName',
            'risk',
            'can',
            'cannot',
            'requiredEnvVars',
            'commandTemplates',
          ],
          properties: {
            id: { type: 'string' },
            capabilityId: { type: 'string' },
            displayName: { type: 'string' },
            risk: { type: 'string', enum: ['read', 'write', 'admin'] },
            can: { type: 'string' },
            cannot: { type: 'string' },
            requiredEnvVars: { type: 'array', items: { type: 'string' } },
            commandTemplates: { type: 'array', items: { type: 'string' } },
            networkHosts: { type: 'array', items: { type: 'string' } },
          },
        },
      },
      createdAt: isoDateTime,
      updatedAt: isoDateTime,
    },
  },
  SkillListResponse: arrayEnvelope('skills', 'Skill'),
  SkillResponse: envelope('skill', { $ref: '#/components/schemas/Skill' }),
  SkillFilesResponse: {
    type: 'object',
    required: ['skill', 'files'],
    properties: {
      skill: { $ref: '#/components/schemas/Skill' },
      files: { type: 'array', items: metadata },
    },
  },
  SkillFileResponse: envelope('file', metadata),
  AgentSkillBindingResponse: envelope('binding', metadata),
  AgentSkillBindingRequest: {
    type: 'object',
    properties: {
      appId: { type: 'string' },
      required: { type: 'boolean' },
    },
  },
  AgentSkillBindingListResponse: envelope('bindings', {
    type: 'array',
    items: metadata,
  }),
  McpServer: {
    type: 'object',
    required: ['id', 'appId', 'name', 'status'],
    properties: {
      id: { type: 'string' },
      appId: { type: 'string' },
      name: { type: 'string' },
      displayName: { type: 'string' },
      description: { type: 'string' },
      status: { type: 'string' },
      transport: { type: 'string' },
      config: metadata,
      allowedToolPatterns: stringArray,
      autoApproveToolPatterns: stringArray,
      credentialRefs: { type: 'array', items: metadata },
      networkHosts: stringArray,
      sandboxProfileId: { type: 'string' },
      createdAt: isoDateTime,
      updatedAt: isoDateTime,
    },
  },
  McpServerPageResponse: {
    type: 'object',
    properties: {
      servers: {
        type: 'array',
        items: { $ref: '#/components/schemas/McpServer' },
      },
      nextCursor: { type: ['string', 'null'] },
    },
  },
  McpServerRequest: {
    type: 'object',
    required: ['name', 'transport', 'config'],
    properties: {
      appId: { type: 'string' },
      name: { type: 'string' },
      displayName: { type: 'string' },
      description: { type: 'string' },
      transport: { type: 'string' },
      config: metadata,
      allowedToolPatterns: stringArray,
      autoApproveToolPatterns: stringArray,
      credentialRefs: { type: 'array', items: metadata },
      networkHosts: stringArray,
      sandboxProfileId: { type: 'string' },
      riskClass: { type: 'string' },
    },
  },
  McpServerResponse: envelope('server', {
    $ref: '#/components/schemas/McpServer',
  }),
  McpServerTestRequest: {
    type: 'object',
    properties: {
      appId: { type: 'string' },
      testedBy: { type: 'string' },
    },
  },
  McpServerTestResponse: {
    type: 'object',
    required: ['ok', 'message', 'server'],
    properties: {
      ok: { type: 'boolean' },
      message: { type: 'string' },
      server: { $ref: '#/components/schemas/McpServer' },
    },
  },
  AgentMcpServerBindingResponse: envelope('binding', metadata),
  AgentMcpServerBindingRequest: {
    type: 'object',
    properties: {
      appId: { type: 'string' },
      required: { type: 'boolean' },
      permissionPolicyIds: stringArray,
      allowedToolPatterns: stringArray,
    },
  },
  AgentMcpServerBindingListResponse: envelope('bindings', {
    type: 'array',
    items: metadata,
  }),
};
