import type { RunnerSandboxProvider, RunnerSandboxResourceLimits } from '../shared/runner-sandbox-provider.js';
import type { AsyncCommandLaunchControl, AsyncCommandProcessHandle } from './async-command-task-service.js';
import type { AsyncCommandOutputSnapshot } from './async-command-task-helpers.js';
export declare const DEFAULT_ASYNC_COMMAND_TIMEOUT_MS = 120000;
export declare const DEFAULT_ASYNC_RESOURCE_LIMITS: RunnerSandboxResourceLimits;
export declare function runSandboxedAsyncCommand(provider: RunnerSandboxProvider, input: {
    command: string;
    cwd: string;
    env: NodeJS.ProcessEnv;
    timeoutMs: number;
    outputMaxBytes: number;
    protectedReadPaths: string[];
    protectedWritePaths: string[];
    allowedNetworkHosts: string[];
    egressProxyUrl?: string;
    resourceLimits: RunnerSandboxResourceLimits;
    signal: AbortSignal;
    appId: string;
    agentId: string;
    conversationId: string;
    threadId?: string | null;
    parentRunId?: string | null;
    parentJobId?: string | null;
    onProcessStarted?: (handle: AsyncCommandProcessHandle) => Promise<void> | void;
    onOutputSnapshot?: (snapshot: AsyncCommandOutputSnapshot) => unknown;
    launchControl?: AsyncCommandLaunchControl;
}): Promise<{
    outputSummary?: string;
    errorSummary?: string;
}>;
export declare function buildAsyncCommandEnv(): Record<string, string>;
