import type { AgentPersona } from '../../../../shared/agent-persona.js';
import type { YoloModeSettings } from '../../../../shared/yolo-mode-policy.js';
import type { PermissionMode } from '../../../../shared/permission-mode.js';
import type { DeepAgentSkillProjection } from '../../../../application/agent-execution/agent-execution-adapter.js';
import type { GantryAgentPromptMode } from '../../../../runner/gantry-agent-system-prompt.js';
import type { AgentControlEffort, AgentControlThinking } from '../../../../domain/types.js';
import type { DeepAgentCheckpointerConfig } from './session-store.js';
import type { DeclarativeToolRule } from '../../../../runner/tool-gate-core.js';
import type { CallableAgentToolManifestEntry } from '../../../../application/core-tools/callable-agent-tools.js';
export interface DeepAgentRunnerInput {
    prompt: string;
    appId?: string;
    agentId?: string;
    sessionId?: string;
    workspaceFolder: string;
    chatJid: string;
    threadId?: string;
    persona?: AgentPersona;
    allowedTools?: string[];
    toolRules?: DeclarativeToolRule[];
    hideAuthorityTools?: boolean;
    callableAgentManifest?: CallableAgentToolManifestEntry[];
    isScheduledJob?: boolean;
    jobId?: string;
    runId?: string;
    assistantName?: string;
    promptMode?: GantryAgentPromptMode;
    compiledSystemPrompt?: string;
    memoryContextBlock?: string;
    effort?: AgentControlEffort;
    configuredThinking?: AgentControlThinking;
    maxOutputTokens?: number;
    deepAgentCheckpointer?: DeepAgentCheckpointerConfig;
    deepAgentSkills?: DeepAgentSkillProjection;
    modelCredentialEnv?: Record<string, string>;
    toolNetworkEnv?: Record<string, string>;
    yoloMode?: YoloModeSettings;
    permissionMode: PermissionMode;
}
